package organizationApp.model.view;

import javax.el.ELContext;
import javax.el.ExpressionFactory;
import javax.el.ValueExpression;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;

import organizationApp.model.entity.OrgFyEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 09 15:26:43 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrgFyVORowImpl extends ViewRowImpl {


    public static final int ENTITY_ORGFYEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        OrgId {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgId((String)value);
            }
        }
        ,
        OrgFyId {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgFyId();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgFyId((Integer)value);
            }
        }
        ,
        FyType {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyType();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyType((String)value);
            }
        }
        ,
        OrgFyEntId {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgFyEntId();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgFyEntId((Integer)value);
            }
        }
        ,
        UsrIdCreate {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getUsrIdCreate();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setUsrIdCreate((Integer)value);
            }
        }
        ,
        UsrIdCreateDt {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getUsrIdCreateDt();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setUsrIdCreateDt((Date)value);
            }
        }
        ,
        UsrIdMod {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getUsrIdMod();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setUsrIdMod((Integer)value);
            }
        }
        ,
        UsrIdModDt {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getUsrIdModDt();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setUsrIdModDt((Date)value);
            }
        }
        ,
        OrgFyAlwOpbalUpdFrmPfy {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgFyAlwOpbalUpdFrmPfy();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgFyAlwOpbalUpdFrmPfy((String)value);
            }
        }
        ,
        OrgFyAlwOpbalUpdToNfy {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgFyAlwOpbalUpdToNfy();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgFyAlwOpbalUpdToNfy((String)value);
            }
        }
        ,
        OrgFyTrfStat {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgFyTrfStat();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgFyTrfStat((String)value);
            }
        }
        ,
        OrgFyTrfTyp {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgFyTrfTyp();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgFyTrfTyp((String)value);
            }
        }
        ,
        OrgFyBcStat {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgFyBcStat();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgFyBcStat((String)value);
            }
        }
        ,
        FyDesc {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyDesc();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyDesc((String)value);
            }
        }
        ,
        FyStrtDy {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyStrtDy();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyStrtDy((Integer)value);
            }
        }
        ,
        FyStrtMn {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyStrtMn();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyStrtMn((Integer)value);
            }
        }
        ,
        FyStrtYr {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyStrtYr();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyStrtYr((Integer)value);
            }
        }
        ,
        FyEndDy {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyEndDy();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyEndDy((Integer)value);
            }
        }
        ,
        FyEndMn {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyEndMn();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyEndMn((Integer)value);
            }
        }
        ,
        FyEndYr {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyEndYr();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyEndYr((Integer)value);
            }
        }
        ,
        FyStrt {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyStrt();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyStrt((Timestamp)value);
            }
        }
        ,
        FyEnd {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyEnd();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setFyEnd((Timestamp)value);
            }
        }
        ,
        OrgSchIdBs {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgSchIdBs();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgSchIdBs((Integer)value);
            }
        }
        ,
        OrgSchIdPnl {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgSchIdPnl();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgSchIdPnl((Integer)value);
            }
        }
        ,
        CldId {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getCldId();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setCldId((String)value);
            }
        }
        ,
        OrgFyRefSlocId {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgFyRefSlocId();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgFyRefSlocId((Integer)value);
            }
        }
        ,
        OrgIdTrans {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgIdTrans();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setOrgIdTrans((String)value);
            }
        }
        ,
        OrgDocFy {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getOrgDocFy();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FyTypeVO1 {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getFyTypeVO1();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LOV_TrfVO1 {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getLOV_TrfVO1();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LovSchdlVO1 {
            public Object get(OrgFyVORowImpl obj) {
                return obj.getLovSchdlVO1();
            }

            public void put(OrgFyVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(OrgFyVORowImpl object);

        public abstract void put(OrgFyVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ORGFYID = AttributesEnum.OrgFyId.index();
    public static final int FYTYPE = AttributesEnum.FyType.index();
    public static final int ORGFYENTID = AttributesEnum.OrgFyEntId.index();
    public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
    public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
    public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
    public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
    public static final int ORGFYALWOPBALUPDFRMPFY = AttributesEnum.OrgFyAlwOpbalUpdFrmPfy.index();
    public static final int ORGFYALWOPBALUPDTONFY = AttributesEnum.OrgFyAlwOpbalUpdToNfy.index();
    public static final int ORGFYTRFSTAT = AttributesEnum.OrgFyTrfStat.index();
    public static final int ORGFYTRFTYP = AttributesEnum.OrgFyTrfTyp.index();
    public static final int ORGFYBCSTAT = AttributesEnum.OrgFyBcStat.index();
    public static final int FYDESC = AttributesEnum.FyDesc.index();
    public static final int FYSTRTDY = AttributesEnum.FyStrtDy.index();
    public static final int FYSTRTMN = AttributesEnum.FyStrtMn.index();
    public static final int FYSTRTYR = AttributesEnum.FyStrtYr.index();
    public static final int FYENDDY = AttributesEnum.FyEndDy.index();
    public static final int FYENDMN = AttributesEnum.FyEndMn.index();
    public static final int FYENDYR = AttributesEnum.FyEndYr.index();
    public static final int FYSTRT = AttributesEnum.FyStrt.index();
    public static final int FYEND = AttributesEnum.FyEnd.index();
    public static final int ORGSCHIDBS = AttributesEnum.OrgSchIdBs.index();
    public static final int ORGSCHIDPNL = AttributesEnum.OrgSchIdPnl.index();
    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int ORGFYREFSLOCID = AttributesEnum.OrgFyRefSlocId.index();
    public static final int ORGIDTRANS = AttributesEnum.OrgIdTrans.index();
    public static final int ORGDOCFY = AttributesEnum.OrgDocFy.index();
    public static final int FYTYPEVO1 = AttributesEnum.FyTypeVO1.index();
    public static final int LOV_TRFVO1 = AttributesEnum.LOV_TrfVO1.index();
    public static final int LOVSCHDLVO1 = AttributesEnum.LovSchdlVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OrgFyVORowImpl() {
    }

    /**
     * Gets OrgFyEO entity object.
     * @return the OrgFyEO
     */
    public OrgFyEOImpl getOrgFyEO() {
        return (OrgFyEOImpl)getEntity(ENTITY_ORGFYEO);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for ORG_FY_ID using the alias name OrgFyId.
     * @return the ORG_FY_ID
     */
    public Integer getOrgFyId() {
        return (Integer) getAttributeInternal(ORGFYID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_FY_ID using the alias name OrgFyId.
     * @param value value to set the ORG_FY_ID
     */
    public void setOrgFyId(Integer value) {
        setAttributeInternal(ORGFYID, value);
    }

    /**
     * Gets the attribute value for FY_TYPE using the alias name FyType.
     * @return the FY_TYPE
     */
    public String getFyType() {
        return (String) getAttributeInternal(FYTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_TYPE using the alias name FyType.
     * @param value value to set the FY_TYPE
     */
    public void setFyType(String value) {
        setAttributeInternal(FYTYPE, value);
    }

    /**
     * Gets the attribute value for ORG_FY_ENT_ID using the alias name OrgFyEntId.
     * @return the ORG_FY_ENT_ID
     */
    public Integer getOrgFyEntId() {
        return (Integer) getAttributeInternal(ORGFYENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_FY_ENT_ID using the alias name OrgFyEntId.
     * @param value value to set the ORG_FY_ENT_ID
     */
    public void setOrgFyEntId(Integer value) {
        setAttributeInternal(ORGFYENTID, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @return the USR_ID_CREATE
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @param value value to set the USR_ID_CREATE
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @return the USR_ID_CREATE_DT
     */
    public Date getUsrIdCreateDt() {
        return (Date) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @param value value to set the USR_ID_CREATE_DT
     */
    public void setUsrIdCreateDt(Date value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @return the USR_ID_MOD
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @param value value to set the USR_ID_MOD
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @return the USR_ID_MOD_DT
     */
    public Date getUsrIdModDt() {
        return (Date) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @param value value to set the USR_ID_MOD_DT
     */
    public void setUsrIdModDt(Date value) {
        setAttributeInternal(USRIDMODDT, value);
    }

    /**
     * Gets the attribute value for ORG_FY_ALW_OPBAL_UPD_FRM_PFY using the alias name OrgFyAlwOpbalUpdFrmPfy.
     * @return the ORG_FY_ALW_OPBAL_UPD_FRM_PFY
     */
    public String getOrgFyAlwOpbalUpdFrmPfy() {
        return (String) getAttributeInternal(ORGFYALWOPBALUPDFRMPFY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_FY_ALW_OPBAL_UPD_FRM_PFY using the alias name OrgFyAlwOpbalUpdFrmPfy.
     * @param value value to set the ORG_FY_ALW_OPBAL_UPD_FRM_PFY
     */
    public void setOrgFyAlwOpbalUpdFrmPfy(String value) {
        setAttributeInternal(ORGFYALWOPBALUPDFRMPFY, value);
    }

    /**
     * Gets the attribute value for ORG_FY_ALW_OPBAL_UPD_TO_NFY using the alias name OrgFyAlwOpbalUpdToNfy.
     * @return the ORG_FY_ALW_OPBAL_UPD_TO_NFY
     */
    public String getOrgFyAlwOpbalUpdToNfy() {
        return (String) getAttributeInternal(ORGFYALWOPBALUPDTONFY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_FY_ALW_OPBAL_UPD_TO_NFY using the alias name OrgFyAlwOpbalUpdToNfy.
     * @param value value to set the ORG_FY_ALW_OPBAL_UPD_TO_NFY
     */
    public void setOrgFyAlwOpbalUpdToNfy(String value) {
        setAttributeInternal(ORGFYALWOPBALUPDTONFY, value);
    }

    /**
     * Gets the attribute value for ORG_FY_TRF_STAT using the alias name OrgFyTrfStat.
     * @return the ORG_FY_TRF_STAT
     */
    public String getOrgFyTrfStat() {
        return (String) getAttributeInternal(ORGFYTRFSTAT);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_FY_TRF_STAT using the alias name OrgFyTrfStat.
     * @param value value to set the ORG_FY_TRF_STAT
     */
    public void setOrgFyTrfStat(String value) {
        setAttributeInternal(ORGFYTRFSTAT, value);
    }

    /**
     * Gets the attribute value for ORG_FY_TRF_TYP using the alias name OrgFyTrfTyp.
     * @return the ORG_FY_TRF_TYP
     */
    public String getOrgFyTrfTyp() {
        return (String) getAttributeInternal(ORGFYTRFTYP);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_FY_TRF_TYP using the alias name OrgFyTrfTyp.
     * @param value value to set the ORG_FY_TRF_TYP
     */
    public void setOrgFyTrfTyp(String value) {
        setAttributeInternal(ORGFYTRFTYP, value);
    }

    /**
     * Gets the attribute value for ORG_FY_BC_STAT using the alias name OrgFyBcStat.
     * @return the ORG_FY_BC_STAT
     */
    public String getOrgFyBcStat() {
        System.out.println("value of the check box is==="+(String) getAttributeInternal(ORGFYBCSTAT));
        return (String) getAttributeInternal(ORGFYBCSTAT);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_FY_BC_STAT using the alias name OrgFyBcStat.
     * @param value value to set the ORG_FY_BC_STAT
     */
    public void setOrgFyBcStat(String value) {
        setAttributeInternal(ORGFYBCSTAT, value);
    }

    /**
     * Gets the attribute value for FY_DESC using the alias name FyDesc.
     * @return the FY_DESC
     */
    public String getFyDesc() {
        return (String) getAttributeInternal(FYDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_DESC using the alias name FyDesc.
     * @param value value to set the FY_DESC
     */
    public void setFyDesc(String value) {
        setAttributeInternal(FYDESC, value);
    }

    /**
     * Gets the attribute value for FY_STRT_DY using the alias name FyStrtDy.
     * @return the FY_STRT_DY
     */
    public Integer getFyStrtDy() {
        return (Integer) getAttributeInternal(FYSTRTDY);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_STRT_DY using the alias name FyStrtDy.
     * @param value value to set the FY_STRT_DY
     */
    public void setFyStrtDy(Integer value) {
        setAttributeInternal(FYSTRTDY, value);
    }

    /**
     * Gets the attribute value for FY_STRT_MN using the alias name FyStrtMn.
     * @return the FY_STRT_MN
     */
    public Integer getFyStrtMn() {
        return (Integer) getAttributeInternal(FYSTRTMN);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_STRT_MN using the alias name FyStrtMn.
     * @param value value to set the FY_STRT_MN
     */
    public void setFyStrtMn(Integer value) {
        setAttributeInternal(FYSTRTMN, value);
    }

    /**
     * Gets the attribute value for FY_STRT_YR using the alias name FyStrtYr.
     * @return the FY_STRT_YR
     */
    public Integer getFyStrtYr() {
        return (Integer) getAttributeInternal(FYSTRTYR);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_STRT_YR using the alias name FyStrtYr.
     * @param value value to set the FY_STRT_YR
     */
    public void setFyStrtYr(Integer value) {
        setAttributeInternal(FYSTRTYR, value);
    }

    /**
     * Gets the attribute value for FY_END_DY using the alias name FyEndDy.
     * @return the FY_END_DY
     */
    public Integer getFyEndDy() {
        return (Integer) getAttributeInternal(FYENDDY);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_END_DY using the alias name FyEndDy.
     * @param value value to set the FY_END_DY
     */
    public void setFyEndDy(Integer value) {
        setAttributeInternal(FYENDDY, value);
    }

    /**
     * Gets the attribute value for FY_END_MN using the alias name FyEndMn.
     * @return the FY_END_MN
     */
    public Integer getFyEndMn() {
        return (Integer) getAttributeInternal(FYENDMN);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_END_MN using the alias name FyEndMn.
     * @param value value to set the FY_END_MN
     */
    public void setFyEndMn(Integer value) {
        setAttributeInternal(FYENDMN, value);
    }

    /**
     * Gets the attribute value for FY_END_YR using the alias name FyEndYr.
     * @return the FY_END_YR
     */
    public Integer getFyEndYr() {
        return (Integer) getAttributeInternal(FYENDYR);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_END_YR using the alias name FyEndYr.
     * @param value value to set the FY_END_YR
     */
    public void setFyEndYr(Integer value) {
        setAttributeInternal(FYENDYR, value);
    }

    /**
     * Gets the attribute value for FY_STRT using the alias name FyStrt.
     * @return the FY_STRT
     */
    public Timestamp getFyStrt() {
        return (Timestamp) getAttributeInternal(FYSTRT);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_STRT using the alias name FyStrt.
     * @param value value to set the FY_STRT
     */
    public void setFyStrt(Timestamp value) {
        setAttributeInternal(FYSTRT, value);
    }

    /**
     * Gets the attribute value for FY_END using the alias name FyEnd.
     * @return the FY_END
     */
    public Timestamp getFyEnd() {
        return (Timestamp) getAttributeInternal(FYEND);
    }

    /**
     * Sets <code>value</code> as attribute value for FY_END using the alias name FyEnd.
     * @param value value to set the FY_END
     */
    public void setFyEnd(Timestamp value) {
        setAttributeInternal(FYEND, value);
    }

    /**
     * Gets the attribute value for ORG_SCH_ID_BS using the alias name OrgSchIdBs.
     * @return the ORG_SCH_ID_BS
     */
    public Integer getOrgSchIdBs() {
        return (Integer) getAttributeInternal(ORGSCHIDBS);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_SCH_ID_BS using the alias name OrgSchIdBs.
     * @param value value to set the ORG_SCH_ID_BS
     */
    public void setOrgSchIdBs(Integer value) {
        setAttributeInternal(ORGSCHIDBS, value);
    }

    /**
     * Gets the attribute value for ORG_SCH_ID_PNL using the alias name OrgSchIdPnl.
     * @return the ORG_SCH_ID_PNL
     */
    public Integer getOrgSchIdPnl() {
        return (Integer) getAttributeInternal(ORGSCHIDPNL);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_SCH_ID_PNL using the alias name OrgSchIdPnl.
     * @param value value to set the ORG_SCH_ID_PNL
     */
    public void setOrgSchIdPnl(Integer value) {
        setAttributeInternal(ORGSCHIDPNL, value);
    }

    /**
     * Gets the attribute value for CLD_ID using the alias name CldId.
     * @return the CLD_ID
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLD_ID using the alias name CldId.
     * @param value value to set the CLD_ID
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for ORG_FY_REF_SLOC_ID using the alias name OrgFyRefSlocId.
     * @return the ORG_FY_REF_SLOC_ID
     */
    public Integer getOrgFyRefSlocId() {
        return (Integer) getAttributeInternal(ORGFYREFSLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_FY_REF_SLOC_ID using the alias name OrgFyRefSlocId.
     * @param value value to set the ORG_FY_REF_SLOC_ID
     */
    public void setOrgFyRefSlocId(Integer value) {
        setAttributeInternal(ORGFYREFSLOCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgIdTrans.
     * @return the OrgIdTrans
     */
    public String getOrgIdTrans() {
        StringBuffer orgId = new StringBuffer(resolvEl("#{pageFlowScope.GLBL_APP_USR_ORG}"));
        System.out.println("OrgId :"+orgId);
        return orgId.toString();
    }
    
    /* Method for resolving the El
    */
    public String resolvEl(String data) {
       FacesContext fc = FacesContext.getCurrentInstance();
       Application app = fc.getApplication();
       ExpressionFactory elFactory = app.getExpressionFactory();
       ELContext elContext = fc.getELContext();
       ValueExpression valueExp = elFactory.createValueExpression(elContext, data, Object.class);
       String Message = valueExp.getValue(elContext).toString();
       return Message;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgIdTrans.
     * @param value value to set the  OrgIdTrans
     */
    public void setOrgIdTrans(String value) {
        setAttributeInternal(ORGIDTRANS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OrgDocFy.
     */
    public RowIterator getOrgDocFy() {
        return (RowIterator)getAttributeInternal(ORGDOCFY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FyTypeVO1.
     */
    public RowSet getFyTypeVO1() {
        return (RowSet)getAttributeInternal(FYTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LOV_TrfVO1.
     */
    public RowSet getLOV_TrfVO1() {
        return (RowSet)getAttributeInternal(LOV_TRFVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovSchdlVO1.
     */
    public RowSet getLovSchdlVO1() {
        return (RowSet)getAttributeInternal(LOVSCHDLVO1);
    }


    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
