package scinvoiceapp.model.views;


import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 20 11:51:58 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MmScInvcPmtSchdlVORowImpl extends ViewRowImpl {


    public static final int ENTITY_MMSCINVCPMTSCHDLEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CldId,
        SlocId,
        OrgId,
        DocId,
        SrNo,
        PayDt,
        PayMode,
        TotAmtSp,
        TotAmtBs,
        PayAmtSp,
        PayAmtBs,
        AdvFlg,
        AdjFlg,
        LovPayModeVO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int SLOCID = AttributesEnum.SlocId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int SRNO = AttributesEnum.SrNo.index();
    public static final int PAYDT = AttributesEnum.PayDt.index();
    public static final int PAYMODE = AttributesEnum.PayMode.index();
    public static final int TOTAMTSP = AttributesEnum.TotAmtSp.index();
    public static final int TOTAMTBS = AttributesEnum.TotAmtBs.index();
    public static final int PAYAMTSP = AttributesEnum.PayAmtSp.index();
    public static final int PAYAMTBS = AttributesEnum.PayAmtBs.index();
    public static final int ADVFLG = AttributesEnum.AdvFlg.index();
    public static final int ADJFLG = AttributesEnum.AdjFlg.index();
    public static final int LOVPAYMODEVO1 = AttributesEnum.LovPayModeVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MmScInvcPmtSchdlVORowImpl() {
    }

    /**
     * Gets MmScInvcPmtSchdlEO entity object.
     * @return the MmScInvcPmtSchdlEO
     */
    public EntityImpl getMmScInvcPmtSchdlEO() {
        return (EntityImpl) getEntity(ENTITY_MMSCINVCPMTSCHDLEO);
    }

    /**
     * Gets the attribute value for CLD_ID using the alias name CldId.
     * @return the CLD_ID
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLD_ID using the alias name CldId.
     * @param value value to set the CLD_ID
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for SLOC_ID using the alias name SlocId.
     * @return the SLOC_ID
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SLOC_ID using the alias name SlocId.
     * @param value value to set the SLOC_ID
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for DOC_ID using the alias name DocId.
     * @return the DOC_ID
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId.
     * @param value value to set the DOC_ID
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for SR_NO using the alias name SrNo.
     * @return the SR_NO
     */
    public Integer getSrNo() {
        return (Integer) getAttributeInternal(SRNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SR_NO using the alias name SrNo.
     * @param value value to set the SR_NO
     */
    public void setSrNo(Integer value) {
        setAttributeInternal(SRNO, value);
    }

    /**
     * Gets the attribute value for PAY_DT using the alias name PayDt.
     * @return the PAY_DT
     */
    public Timestamp getPayDt() {
        return (Timestamp) getAttributeInternal(PAYDT);
    }

    /**
     * Sets <code>value</code> as attribute value for PAY_DT using the alias name PayDt.
     * @param value value to set the PAY_DT
     */
    public void setPayDt(Timestamp value) {
        setAttributeInternal(PAYDT, value);
    }

    /**
     * Gets the attribute value for PAY_MODE using the alias name PayMode.
     * @return the PAY_MODE
     */
    public Integer getPayMode() {
        return (Integer) getAttributeInternal(PAYMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAY_MODE using the alias name PayMode.
     * @param value value to set the PAY_MODE
     */
    public void setPayMode(Integer value) {
        setAttributeInternal(PAYMODE, value);
    }

    /**
     * Gets the attribute value for TOT_AMT_SP using the alias name TotAmtSp.
     * @return the TOT_AMT_SP
     */
    public oracle.jbo.domain.Number getTotAmtSp() {
        return (oracle.jbo.domain.Number) getAttributeInternal(TOTAMTSP);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_AMT_SP using the alias name TotAmtSp.
     * @param value value to set the TOT_AMT_SP
     */
    public void setTotAmtSp(oracle.jbo.domain.Number value) {
        setAttributeInternal(TOTAMTSP, value);
    }

    /**
     * Gets the attribute value for TOT_AMT_BS using the alias name TotAmtBs.
     * @return the TOT_AMT_BS
     */
    public oracle.jbo.domain.Number getTotAmtBs() {
        return (oracle.jbo.domain.Number) getAttributeInternal(TOTAMTBS);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_AMT_BS using the alias name TotAmtBs.
     * @param value value to set the TOT_AMT_BS
     */
    public void setTotAmtBs(oracle.jbo.domain.Number value) {
        setAttributeInternal(TOTAMTBS, value);
    }

    /**
     * Gets the attribute value for PAY_AMT_SP using the alias name PayAmtSp.
     * @return the PAY_AMT_SP
     */
    public oracle.jbo.domain.Number getPayAmtSp() {
        return (oracle.jbo.domain.Number) getAttributeInternal(PAYAMTSP);
    }

    /**
     * Sets <code>value</code> as attribute value for PAY_AMT_SP using the alias name PayAmtSp.
     * @param value value to set the PAY_AMT_SP
     */
    public void setPayAmtSp(oracle.jbo.domain.Number value) {
        setAttributeInternal(PAYAMTSP, value);
    }

    /**
     * Gets the attribute value for PAY_AMT_BS using the alias name PayAmtBs.
     * @return the PAY_AMT_BS
     */
    public oracle.jbo.domain.Number getPayAmtBs() {
        return (oracle.jbo.domain.Number) getAttributeInternal(PAYAMTBS);
    }

    /**
     * Sets <code>value</code> as attribute value for PAY_AMT_BS using the alias name PayAmtBs.
     * @param value value to set the PAY_AMT_BS
     */
    public void setPayAmtBs(oracle.jbo.domain.Number value) {
        setAttributeInternal(PAYAMTBS, value);
    }

    /**
     * Gets the attribute value for ADV_FLG using the alias name AdvFlg.
     * @return the ADV_FLG
     */
    public String getAdvFlg() {
        return (String) getAttributeInternal(ADVFLG);
    }

    /**
     * Sets <code>value</code> as attribute value for ADV_FLG using the alias name AdvFlg.
     * @param value value to set the ADV_FLG
     */
    public void setAdvFlg(String value) {
        setAttributeInternal(ADVFLG, value);
    }

    /**
     * Gets the attribute value for ADJ_FLG using the alias name AdjFlg.
     * @return the ADJ_FLG
     */
    public String getAdjFlg() {
        return (String) getAttributeInternal(ADJFLG);
    }

    /**
     * Sets <code>value</code> as attribute value for ADJ_FLG using the alias name AdjFlg.
     * @param value value to set the ADJ_FLG
     */
    public void setAdjFlg(String value) {
        setAttributeInternal(ADJFLG, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovPayModeVO1.
     */
    public RowSet getLovPayModeVO1() {
        return (RowSet) getAttributeInternal(LOVPAYMODEVO1);
    }
}

