package assetliabprd.model.module;

import assetliabprd.model.module.common.AssetLiabilityPrdAM;

import assetliabprd.model.views.SearchVOImpl;

import java.util.Date;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 01 16:30:02 IST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssetLiabilityPrdAMImpl extends ApplicationModuleImpl implements AssetLiabilityPrdAM {
    /**
     * This is the default constructor (do not remove).
     */
    public AssetLiabilityPrdAMImpl() {

    }


    /**
     * This method has been called as first activity
     * **/
    public void setGlobalParameters() {
        ViewObjectImpl assetLiabilityMstVO = this.getAssetLiabilityMstVO();
        assetLiabilityMstVO.setNamedWhereClauseParam("BindCldId", -1);
        assetLiabilityMstVO.executeQuery();

    }


    /**
     * Container's getter for AssetLiabilityMstVO.
     * @return AssetLiabilityMstVO
     */
    public ViewObjectImpl getAssetLiabilityMstVO() {
        return (ViewObjectImpl) findViewObject("AssetLiabilityMstVO");
    }


    /**
     * Container's getter for SearchVO1.
     * @return SearchVO1
     */
    public SearchVOImpl getSearchVO1() {
        return (SearchVOImpl) findViewObject("SearchVO1");
    }

    /**
     * Container's getter for SearchPrdVO1.
     * @return SearchPrdVO1
     */
    public ViewObjectImpl getSearchPrdVO1() {
        return (ViewObjectImpl) findViewObject("SearchPrdVO1");
    }


    /**
     * Container's getter for AssetLiabilityMstVO2.
     * @return AssetLiabilityMstVO2
     */
    public ViewObjectImpl getAssetLiabilityMstVO2() {
        return (ViewObjectImpl) findViewObject("AssetLiabilityMstVO2");
    }

    /**
     * Container's getter for AssetLiabilityMstVO1.
     * @return AssetLiabilityMstVO1
     */
    public ViewObjectImpl getAssetLiabilityMstVO1() {
        return (ViewObjectImpl) findViewObject("AssetLiabilityMstVO1");
    }

    /**
     * Container's getter for AssetLiabilityPrdVO1.
     * @return AssetLiabilityPrdVO1
     */
    public ViewObjectImpl getAssetLiabilityPrdVO1() {
        return (ViewObjectImpl) findViewObject("AssetLiabilityPrdVO1");
    }
}
