package mmpurchasereturn.model.views;

import mmpurchasereturn.model.services.MmPurchaseReturnAMImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 17 11:30:40 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LotBinSuppVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CldId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getCldId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SlocId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getSlocId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrgId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FyId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getFyId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WhId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getWhId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EoId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getEoId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItmId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getItmId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItmUomBs {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getItmUomBs();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LotId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getLotId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BinId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getBinId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TotStk {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getTotStk();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RejStk {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getRejStk();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        RwkStk {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getRwkStk();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DocId {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getDocId();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ExtDocNo {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getExtDocNo();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TransOkQtyBin {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getTransOkQtyBin();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setTransOkQtyBin((Number) value);
            }
        }
        ,
        TransRejQtyBin {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getTransRejQtyBin();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setTransRejQtyBin((Number) value);
            }
        }
        ,
        TransRewQtyBin {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getTransRewQtyBin();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setTransRewQtyBin((Number) value);
            }
        }
        ,
        BinNameTrans {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getBinNameTrans();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setBinNameTrans((String) value);
            }
        }
        ,
        LovBinNmVO1 {
            public Object get(LotBinSuppVORowImpl obj) {
                return obj.getLovBinNmVO1();
            }

            public void put(LotBinSuppVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(LotBinSuppVORowImpl object);

        public abstract void put(LotBinSuppVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int SLOCID = AttributesEnum.SlocId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int FYID = AttributesEnum.FyId.index();
    public static final int WHID = AttributesEnum.WhId.index();
    public static final int EOID = AttributesEnum.EoId.index();
    public static final int ITMID = AttributesEnum.ItmId.index();
    public static final int ITMUOMBS = AttributesEnum.ItmUomBs.index();
    public static final int LOTID = AttributesEnum.LotId.index();
    public static final int BINID = AttributesEnum.BinId.index();
    public static final int TOTSTK = AttributesEnum.TotStk.index();
    public static final int REJSTK = AttributesEnum.RejStk.index();
    public static final int RWKSTK = AttributesEnum.RwkStk.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int EXTDOCNO = AttributesEnum.ExtDocNo.index();
    public static final int TRANSOKQTYBIN = AttributesEnum.TransOkQtyBin.index();
    public static final int TRANSREJQTYBIN = AttributesEnum.TransRejQtyBin.index();
    public static final int TRANSREWQTYBIN = AttributesEnum.TransRewQtyBin.index();
    public static final int BINNAMETRANS = AttributesEnum.BinNameTrans.index();
    public static final int LOVBINNMVO1 = AttributesEnum.LovBinNmVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LotBinSuppVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CldId.
     * @return the CldId
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Gets the attribute value for the calculated attribute SlocId.
     * @return the SlocId
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgId.
     * @return the OrgId
     */
    public String getOrgId() {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Gets the attribute value for the calculated attribute FyId.
     * @return the FyId
     */
    public Integer getFyId() {
        return (Integer) getAttributeInternal(FYID);
    }

    /**
     * Gets the attribute value for the calculated attribute WhId.
     * @return the WhId
     */
    public String getWhId() {
        return (String) getAttributeInternal(WHID);
    }

    /**
     * Gets the attribute value for the calculated attribute EoId.
     * @return the EoId
     */
    public Integer getEoId() {
        return (Integer) getAttributeInternal(EOID);
    }

    /**
     * Gets the attribute value for the calculated attribute ItmId.
     * @return the ItmId
     */
    public String getItmId() {
        return (String) getAttributeInternal(ITMID);
    }

    /**
     * Gets the attribute value for the calculated attribute ItmUomBs.
     * @return the ItmUomBs
     */
    public String getItmUomBs() {
        return (String) getAttributeInternal(ITMUOMBS);
    }

    /**
     * Gets the attribute value for the calculated attribute LotId.
     * @return the LotId
     */
    public String getLotId() {
        return (String) getAttributeInternal(LOTID);
    }

    /**
     * Gets the attribute value for the calculated attribute BinId.
     * @return the BinId
     */
    public String getBinId() {
        return (String) getAttributeInternal(BINID);
    }

    /**
     * Gets the attribute value for the calculated attribute TotStk.
     * @return the TotStk
     */
    public Number getTotStk() {
        return (Number) getAttributeInternal(TOTSTK);
    }

    /**
     * Gets the attribute value for the calculated attribute RejStk.
     * @return the RejStk
     */
    public Number getRejStk() {
        return (Number) getAttributeInternal(REJSTK);
    }

    /**
     * Gets the attribute value for the calculated attribute RwkStk.
     * @return the RwkStk
     */
    public Number getRwkStk() {
        return (Number) getAttributeInternal(RWKSTK);
    }


    /**
     * Gets the attribute value for the calculated attribute DocId.
     * @return the DocId
     */
    public String getDocId() {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Gets the attribute value for the calculated attribute ExtDocNo.
     * @return the ExtDocNo
     */
    public String getExtDocNo() {
        return (String) getAttributeInternal(EXTDOCNO);
    }

    /**
     * Gets the attribute value for the calculated attribute TransOkQtyBin.
     * @return the TransOkQtyBin
     */
    public Number getTransOkQtyBin() {
        return (Number) getAttributeInternal(TRANSOKQTYBIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransOkQtyBin.
     * @param value value to set the  TransOkQtyBin
     */
    public void setTransOkQtyBin(Number value) {
        setAttributeInternal(TRANSOKQTYBIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRejQtyBin.
     * @return the TransRejQtyBin
     */
    public Number getTransRejQtyBin() {
        return (Number) getAttributeInternal(TRANSREJQTYBIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRejQtyBin.
     * @param value value to set the  TransRejQtyBin
     */
    public void setTransRejQtyBin(Number value) {
        setAttributeInternal(TRANSREJQTYBIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransRewQtyBin.
     * @return the TransRewQtyBin
     */
    public Number getTransRewQtyBin() {
        return (Number) getAttributeInternal(TRANSREWQTYBIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransRewQtyBin.
     * @param value value to set the  TransRewQtyBin
     */
    public void setTransRewQtyBin(Number value) {
        setAttributeInternal(TRANSREWQTYBIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BinNameTrans.
     * @return the BinNameTrans
     */
    public String getBinNameTrans() {
        if (getBinId() != null) {
            MmPurchaseReturnAMImpl am = (MmPurchaseReturnAMImpl) this.getApplicationModule();
            ViewObjectImpl binVo = am.getLovBinNm1();
           ViewCriteria vc = binVo.getViewCriteria("LovBinNmVOCriteria");
          binVo.applyViewCriteria(vc);
            binVo.setNamedWhereClauseParam("BindBinId", getBinId());
            binVo.setNamedWhereClauseParam("BindWhId", getWhId());
            binVo.setNamedWhereClauseParam("BindOrgId", getOrgId());
            binVo.setNamedWhereClauseParam("BindCldId", getCldId());
            binVo.setNamedWhereClauseParam("BindSlocId", getSlocId());
            binVo.executeQuery();
            Row[] rr = binVo.getFilteredRows("BinId", getBinId());
            System.out.println("--lot bin name length---"+ rr.length);
            if (rr.length > 0 && rr[0].getAttribute("BinNm") != null) {
            System.out.println("--lot bin name---"+  rr[0].getAttribute("BinNm").toString()+" "+getBinId());
                return rr[0].getAttribute("BinNm").toString();

            } else {
                return (String) getAttributeInternal(BINNAMETRANS);
            }
        }
        
        return (String) getAttributeInternal(BINNAMETRANS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BinNameTrans.
     * @param value value to set the  BinNameTrans
     */
    public void setBinNameTrans(String value) {
        setAttributeInternal(BINNAMETRANS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovBinNmVO1.
     */
    public RowSet getLovBinNmVO1() {
        return (RowSet) getAttributeInternal(LOVBINNMVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}

