package slsquotationapp.model.bundle;

import java.util.ListResourceBundle;

public class Resource extends ListResourceBundle {
    private static final Object[][] contents = { { "slsquotationapp.model.views.LOVPaymntModeVO_LABEL", "Lov Paymnt Mode Vo" }, { "slsquotationapp.model.views.LOVDiscTypVO_LABEL", "Lov Disc Typ Vo" }, { "slsquotationapp.model.views.LOVEoTypVO_LABEL", "Lov Eo Typ Vo" },
      { "slsquotationapp.model.views.LOVSpCurrencyVO_LABEL", "Lov Sp Currency Vo" }, { "slsquotationapp.model.views.EoAddTempVO_LABEL", "Eo Add Temp Vo" }, { "slsquotationapp.model.views.LOVAppSecUserVO_LABEL", "Lov App Sec User Vo" }, { "slsquotationapp.model.views.LOVItemVO_LABEL", "Lov Item Vo" }, { "slsquotationapp.model.links.QuoteToItemVL_LABEL", "View Link Vl" }, { "slsquotationapp.model.views.LOVUOMVO_LABEL", "Lovuomvo" }, { "slsquotationapp.model.views.LOVTaxRuleVO_LABEL", "Lov Tax Rule Vo" }, { "slsquotationapp.model.links.ItemTOTrVL_LABEL", "Item To Tr Vl" }, { "slsquotationapp.model.links.TrTOTrLinesVL_LABEL", "Tr To Tr Lines Vl" }, { "slsquotationapp.model.views.LOVTaxRuleLinesCOAVO_LABEL", "Lov Tax Rule Lines Coavo" }, { "slsquotationapp.model.views.LOVCoaVO_LABEL", "Lov Coa Vo" }, { "slsquotationapp.model.views.searchVO_LABEL", "Search Vo" }, { "slsquotationapp.model.views.SearchQuotationVO_LABEL", "Search Quotation Vo" }, { "slsquotationapp.model.views.searchQuotationVO_LABEL", "Search Quotation Vo" }, { "slsquotationapp.model.links.ItmToVL_LABEL", "Itm To Vl" }, { "slsquotationapp.model.views.LOVSchemeVO_LABEL", "Lov Scheme Vo" }, { "slsquotationapp.model.links.ItemToSchemeVL_LABEL", "Item To Scheme Vl" }, { "slsquotationapp.model.views.LOVTaxType_LABEL", "Lov Tax Type" }, { "slsquotationapp.model.links.QuotTOTrVL_LABEL", "Quot To Tr Vl" }, { "slsquotationapp.model.views.LOVDiscountOrderVO_LABEL", "Lov Discount Order Vo" }, { "slsquotationapp.model.views.SlsQuotCalcVO_LABEL", "Sls Quot Calc Vo" }, { "slsquotationapp.model.links.QuoteTOCalcVL_LABEL", "Quote To Calc Vl" },
      { "slsquotationapp.model.links.QuotTOTnCVL_LABEL", "Quot To Tn Cvl" }, { "slsquotationapp.model.views.TnCVO_LABEL", "Tn Cvo" }, { "slsquotationapp.model.views.LOVTnCVO_LABEL", "Lov Tn Cvo" }, { "slsquotationapp.model.entities.SlsQuotEO.QuotAmtBs_Rule_0", "Invalid precision in Quotation Amount!" }, { "slsquotationapp.model.entities.SlsQuotEO.QuotAmtSp_Rule_0", "Invalid precision in Quotation Amount!" }, { "slsquotationapp.model.entities.SlsQuotEO.CurrConvFctr_Rule_0", "Invalid precision in Cuerrency Conversion factor!" }, { "slsquotationapp.model.entities.SlsQuotItmEO.QuotQty_Rule_0", "Invalid precision in Item Quantity!" }, { "slsquotationapp.model.entities.SlsQuotItmEO.ItmAmtBs_Rule_0", "Invalid precision in Item Total Amount!" }, { "slsquotationapp.model.entities.SlsQuotItmEO.ItmAmtSp_Rule_0", "Invalid precision in Item Total Amount!" }, { "slsquotationapp.model.views.LOVDelvryModeVO_LABEL", "Lov Delvry Mode Vo" }, { "LOV_QuotDelModeId_LOVUIHints_NullValueId", "-- select --" },
        { "slsquotationapp.model.views.LOVEnquiryVO_LABEL", "Lov Enquiry Vo" }, { "slsquotationapp.model.views.InquirySlsOppVO_LABEL", "Inquiry Sls Opp Vo" }, { "slsquotationapp.model.views.InquirySlsOppItmVO_LABEL", "Inquiry Sls Opp Itm Vo" }, { "slsquotationapp.model.links.InquiryOppTOInquiryOppItmVL_LABEL", "Inquiry Opp To Inquiry Opp Itm Vl" }, { "slsquotationapp.model.views.LOVQuotTypeVO_LABEL", "Lov Quot Type Vo" }, { "slsquotationapp.model.views.SLSQuotCalcVO_LABEL", "Sls Quot Calc Vo" }, { "slsquotationapp.model.views.CheckFromPrfVO_LABEL", "Check From Prf Vo" }, { "slsquotationapp.model.views.searchVO.QuotNmTrans_LABEL", "LBL.781" }, { "slsquotationapp.model.views.searchVO.EoName_LABEL", "LBL.1226" }, { "slsquotationapp.model.views.SlsQuotVO.enquiryNmTrans_LABEL", "LBL.2764" }, { "slsquotationapp.model.views.LOVWfStatusVO_LABEL", "Lov Wf Status Vo" }, { "slsquotationapp.model.views.LOVEnquiryVO.DispDocId_LABEL", "LBL.2530" }, { "LBL.781", "LBL.784" }, { "slsquotationapp.model.views.LOVQuotDispIdVO.DispDocId_LABEL", "LBL.784'" }, { "slsquotationapp.model.views.LOVQuotDispIdVO_LABEL", "LBL.784'" }, { "slsquotationapp.model.views.LOVCustomerVO.EoNm_LABEL", "LBL.1226" }, { "LBL.1226", "LBL.1226" }, { "slsquotationapp.model.views.LOVCustomerVO_LABEL", "LBL.1226" }, { "LBL.2530", "LBL.2530" }, { "LBL.784", "LBL.784" }, { "EoShowTrans_LABEL", "LBL.1226" }, { "DispDocId_LABEL", "LBL.2530" }, { "ItmDesc_LABEL", "LBL.528" }, { "QuotNmTrans_LABEL", "LBL.784" }


    };

    public Object[][] getContents() {
        return contents;
    }
}
