package hcmempprfsetup.model.views;

import adf.utils.ebiz.EbizParams;

import hcmempprfsetup.model.entities.OrgHcmEmpPrfEOImpl;

import hcmempprfsetup.model.modules.HcmEmpPrfAMImpl;

import java.math.BigDecimal;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.el.ELContext;
import javax.el.ExpressionFactory;
import javax.el.ValueExpression;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.RowQualifier;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 12 13:07:43 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrgHcmEmpPrfVORowImpl extends ViewRowImpl {


    public static final int ENTITY_ORGHCMEMPPRFEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum
    {
        CldId,
        SlocId,
        HoOrgId,
        OrgId,
        DocId,
        EmpCode,
        EmpId,
        EmpNm,
        EmpNm1,
        EmpNm2,
        EmpNm3,
        EmpNm4,
        EmpCardNo,
        EmpDob,
        EmpDoj,
        EmpDeptId,
        EmpDesgId,
        EmpLocId,
        EmpGrpId,
        WrkStat,
        WrkStatDt,
        EmpGen,
        EmpDedCh,
        EmpPermAdd,
        EmpCurrAdd,
        EmpEmail,
        EmpPhone1,
        EmpPhone2,
        EmpPayMode,
        EmpBnkId,
        BnkBrnchId,
        AccNo,
        AccType,
        UsrIdCreate,
        UsrIdCreateDt,
        UsrIdMod,
        UsrIdModDt,
        ActvFlg,
        IfscCode,
        SwiftCode,
        EmpPanNo,
        EmpEoNm,
        TransGrpDesc,
        TransBnkNm,
        TransBnkBrnchNm,
        TransStrtDtShiftDisp,
        TransEndDtShiftDisp,
        TransStrtDtTimeCal,
        TransEndDtTimeCal,
        TransMode,
        EmpGuardNm,
        EmpRel,
        TransIsEmpEditable,
        ReqAreaFlg,
        TransIsRqmtButtonAvl,
        SponNm,
        EmpMrtlStat,
        EmpNation,
        MgrCode,
        MgrDocId,
        UsrId,
        EmpRetDt,
        EmpConfDt,
        BnkCode,
        EmpWrkHours,
        TransGrpWagesChk,
        EmpBldGrp,
        TransCntryId,
        EmpNotice,
        EmpDol,
        GrdId,
        transGradSalChck,
        transReffraanceEmpChk,
        EmpRefDocId,
        transEmpRefNm,
        EmpType,
        EmpProbation,
        EmpCurrPin,
        EmpPermPin,
        HcmEmpImg,
        HcmEmpSal,
        HcmEmpLeave,
        HcmEmpCalOff,
        HcmEmpShift,
        EmployeeDeduction,
        HcmEmpShiftTmp,
        HcmEmpSkil,
        RqmtArea,
        OrgHcmEmpOthDtl,
        HcmEmpDocAttch,
        HcmEmpDpndDtl,
        HcmEmpMdclDtl,
        HcmEmpExpVo,
        HcmEmpLang,
        HcmEmpQuali,
        LovDesgIdVO,
        LovDeptIdVO,
        LovGrpVO,
        LovGenderVO,
        LovLocationVO,
        LovAccTypeVO,
        LovPayModeVO,
        LovBankIdVO,
        LovBnkBrnchIdVO,
        LovEmpStat,
        LovMaritalStatusVO1,
        LovNationalityVO1,
        LovUsrIdVO1,
        LovManagerVO1,
        LovGrdNmVO1,
        LovEmpNmForReffranceVO1,
        LovEmpTypeO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index()
        {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex()
        {
            return firstIndex;
        }

        public static int count()
        {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues()
        {
            if (vals == null)
            {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int SLOCID = AttributesEnum.SlocId.index();
    public static final int HOORGID = AttributesEnum.HoOrgId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int EMPCODE = AttributesEnum.EmpCode.index();
    public static final int EMPID = AttributesEnum.EmpId.index();
    public static final int EMPNM = AttributesEnum.EmpNm.index();
    public static final int EMPNM1 = AttributesEnum.EmpNm1.index();
    public static final int EMPNM2 = AttributesEnum.EmpNm2.index();
    public static final int EMPNM3 = AttributesEnum.EmpNm3.index();
    public static final int EMPNM4 = AttributesEnum.EmpNm4.index();
    public static final int EMPCARDNO = AttributesEnum.EmpCardNo.index();
    public static final int EMPDOB = AttributesEnum.EmpDob.index();
    public static final int EMPDOJ = AttributesEnum.EmpDoj.index();
    public static final int EMPDEPTID = AttributesEnum.EmpDeptId.index();
    public static final int EMPDESGID = AttributesEnum.EmpDesgId.index();
    public static final int EMPLOCID = AttributesEnum.EmpLocId.index();
    public static final int EMPGRPID = AttributesEnum.EmpGrpId.index();
    public static final int WRKSTAT = AttributesEnum.WrkStat.index();
    public static final int WRKSTATDT = AttributesEnum.WrkStatDt.index();
    public static final int EMPGEN = AttributesEnum.EmpGen.index();
    public static final int EMPDEDCH = AttributesEnum.EmpDedCh.index();
    public static final int EMPPERMADD = AttributesEnum.EmpPermAdd.index();
    public static final int EMPCURRADD = AttributesEnum.EmpCurrAdd.index();
    public static final int EMPEMAIL = AttributesEnum.EmpEmail.index();
    public static final int EMPPHONE1 = AttributesEnum.EmpPhone1.index();
    public static final int EMPPHONE2 = AttributesEnum.EmpPhone2.index();
    public static final int EMPPAYMODE = AttributesEnum.EmpPayMode.index();
    public static final int EMPBNKID = AttributesEnum.EmpBnkId.index();
    public static final int BNKBRNCHID = AttributesEnum.BnkBrnchId.index();
    public static final int ACCNO = AttributesEnum.AccNo.index();
    public static final int ACCTYPE = AttributesEnum.AccType.index();
    public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
    public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
    public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
    public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
    public static final int ACTVFLG = AttributesEnum.ActvFlg.index();
    public static final int IFSCCODE = AttributesEnum.IfscCode.index();
    public static final int SWIFTCODE = AttributesEnum.SwiftCode.index();
    public static final int EMPPANNO = AttributesEnum.EmpPanNo.index();
    public static final int EMPEONM = AttributesEnum.EmpEoNm.index();
    public static final int TRANSGRPDESC = AttributesEnum.TransGrpDesc.index();
    public static final int TRANSBNKNM = AttributesEnum.TransBnkNm.index();
    public static final int TRANSBNKBRNCHNM = AttributesEnum.TransBnkBrnchNm.index();
    public static final int TRANSSTRTDTSHIFTDISP = AttributesEnum.TransStrtDtShiftDisp.index();
    public static final int TRANSENDDTSHIFTDISP = AttributesEnum.TransEndDtShiftDisp.index();
    public static final int TRANSSTRTDTTIMECAL = AttributesEnum.TransStrtDtTimeCal.index();
    public static final int TRANSENDDTTIMECAL = AttributesEnum.TransEndDtTimeCal.index();
    public static final int TRANSMODE = AttributesEnum.TransMode.index();
    public static final int EMPGUARDNM = AttributesEnum.EmpGuardNm.index();
    public static final int EMPREL = AttributesEnum.EmpRel.index();
    public static final int TRANSISEMPEDITABLE = AttributesEnum.TransIsEmpEditable.index();
    public static final int REQAREAFLG = AttributesEnum.ReqAreaFlg.index();
    public static final int TRANSISRQMTBUTTONAVL = AttributesEnum.TransIsRqmtButtonAvl.index();
    public static final int SPONNM = AttributesEnum.SponNm.index();
    public static final int EMPMRTLSTAT = AttributesEnum.EmpMrtlStat.index();
    public static final int EMPNATION = AttributesEnum.EmpNation.index();
    public static final int MGRCODE = AttributesEnum.MgrCode.index();
    public static final int MGRDOCID = AttributesEnum.MgrDocId.index();
    public static final int USRID = AttributesEnum.UsrId.index();
    public static final int EMPRETDT = AttributesEnum.EmpRetDt.index();
    public static final int EMPCONFDT = AttributesEnum.EmpConfDt.index();
    public static final int BNKCODE = AttributesEnum.BnkCode.index();
    public static final int EMPWRKHOURS = AttributesEnum.EmpWrkHours.index();
    public static final int TRANSGRPWAGESCHK = AttributesEnum.TransGrpWagesChk.index();
    public static final int EMPBLDGRP = AttributesEnum.EmpBldGrp.index();
    public static final int TRANSCNTRYID = AttributesEnum.TransCntryId.index();
    public static final int EMPNOTICE = AttributesEnum.EmpNotice.index();
    public static final int EMPDOL = AttributesEnum.EmpDol.index();
    public static final int GRDID = AttributesEnum.GrdId.index();
    public static final int TRANSGRADSALCHCK = AttributesEnum.transGradSalChck.index();
    public static final int TRANSREFFRAANCEEMPCHK = AttributesEnum.transReffraanceEmpChk.index();
    public static final int EMPREFDOCID = AttributesEnum.EmpRefDocId.index();
    public static final int TRANSEMPREFNM = AttributesEnum.transEmpRefNm.index();
    public static final int EMPTYPE = AttributesEnum.EmpType.index();
    public static final int EMPPROBATION = AttributesEnum.EmpProbation.index();
    public static final int EMPCURRPIN = AttributesEnum.EmpCurrPin.index();
    public static final int EMPPERMPIN = AttributesEnum.EmpPermPin.index();
    public static final int HCMEMPIMG = AttributesEnum.HcmEmpImg.index();
    public static final int HCMEMPSAL = AttributesEnum.HcmEmpSal.index();
    public static final int HCMEMPLEAVE = AttributesEnum.HcmEmpLeave.index();
    public static final int HCMEMPCALOFF = AttributesEnum.HcmEmpCalOff.index();
    public static final int HCMEMPSHIFT = AttributesEnum.HcmEmpShift.index();
    public static final int EMPLOYEEDEDUCTION = AttributesEnum.EmployeeDeduction.index();
    public static final int HCMEMPSHIFTTMP = AttributesEnum.HcmEmpShiftTmp.index();
    public static final int HCMEMPSKIL = AttributesEnum.HcmEmpSkil.index();
    public static final int RQMTAREA = AttributesEnum.RqmtArea.index();
    public static final int ORGHCMEMPOTHDTL = AttributesEnum.OrgHcmEmpOthDtl.index();
    public static final int HCMEMPDOCATTCH = AttributesEnum.HcmEmpDocAttch.index();
    public static final int HCMEMPDPNDDTL = AttributesEnum.HcmEmpDpndDtl.index();
    public static final int HCMEMPMDCLDTL = AttributesEnum.HcmEmpMdclDtl.index();
    public static final int HCMEMPEXPVO = AttributesEnum.HcmEmpExpVo.index();
    public static final int HCMEMPLANG = AttributesEnum.HcmEmpLang.index();
    public static final int HCMEMPQUALI = AttributesEnum.HcmEmpQuali.index();
    public static final int LOVDESGIDVO = AttributesEnum.LovDesgIdVO.index();
    public static final int LOVDEPTIDVO = AttributesEnum.LovDeptIdVO.index();
    public static final int LOVGRPVO = AttributesEnum.LovGrpVO.index();
    public static final int LOVGENDERVO = AttributesEnum.LovGenderVO.index();
    public static final int LOVLOCATIONVO = AttributesEnum.LovLocationVO.index();
    public static final int LOVACCTYPEVO = AttributesEnum.LovAccTypeVO.index();
    public static final int LOVPAYMODEVO = AttributesEnum.LovPayModeVO.index();
    public static final int LOVBANKIDVO = AttributesEnum.LovBankIdVO.index();
    public static final int LOVBNKBRNCHIDVO = AttributesEnum.LovBnkBrnchIdVO.index();
    public static final int LOVEMPSTAT = AttributesEnum.LovEmpStat.index();
    public static final int LOVMARITALSTATUSVO1 = AttributesEnum.LovMaritalStatusVO1.index();
    public static final int LOVNATIONALITYVO1 = AttributesEnum.LovNationalityVO1.index();
    public static final int LOVUSRIDVO1 = AttributesEnum.LovUsrIdVO1.index();
    public static final int LOVMANAGERVO1 = AttributesEnum.LovManagerVO1.index();
    public static final int LOVGRDNMVO1 = AttributesEnum.LovGrdNmVO1.index();
    public static final int LOVEMPNMFORREFFRANCEVO1 = AttributesEnum.LovEmpNmForReffranceVO1.index();
    public static final int LOVEMPTYPEO1 = AttributesEnum.LovEmpTypeO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OrgHcmEmpPrfVORowImpl()
    {
    }

    /**
     * Gets OrgHcmEmpPrfEO entity object.
     * @return the OrgHcmEmpPrfEO
     */
    public OrgHcmEmpPrfEOImpl getOrgHcmEmpPrfEO()
    {
        return (OrgHcmEmpPrfEOImpl) getEntity(ENTITY_ORGHCMEMPPRFEO);
    }

    /**
     * Gets the attribute value for CLD_ID using the alias name CldId.
     * @return the CLD_ID
     */
    public String getCldId()
    {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLD_ID using the alias name CldId.
     * @param value value to set the CLD_ID
     */
    public void setCldId(String value)
    {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for SLOC_ID using the alias name SlocId.
     * @return the SLOC_ID
     */
    public Integer getSlocId()
    {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SLOC_ID using the alias name SlocId.
     * @param value value to set the SLOC_ID
     */
    public void setSlocId(Integer value)
    {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @return the HO_ORG_ID
     */
    public String getHoOrgId()
    {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @param value value to set the HO_ORG_ID
     */
    public void setHoOrgId(String value)
    {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public String getOrgId()
    {
        return (String) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(String value)
    {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for DOC_ID using the alias name DocId.
     * @return the DOC_ID
     */
    public String getDocId()
    {
        return (String) getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOC_ID using the alias name DocId.
     * @param value value to set the DOC_ID
     */
    public void setDocId(String value)
    {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for EMP_CODE using the alias name EmpCode.
     * @return the EMP_CODE
     */
    public Integer getEmpCode()
    {
        return (Integer) getAttributeInternal(EMPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_CODE using the alias name EmpCode.
     * @param value value to set the EMP_CODE
     */
    public void setEmpCode(Integer value)
    {
        setAttributeInternal(EMPCODE, value);
    }

    /**
     * Gets the attribute value for EMP_ID using the alias name EmpId.
     * @return the EMP_ID
     */
    public String getEmpId()
    {
        if (getAttributeInternal(EMPID) != null)
            return ((String) getAttributeInternal(EMPID)).trim();
        else
            return (String) getAttributeInternal(EMPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_ID using the alias name EmpId.
     * @param value value to set the EMP_ID
     */
    public void setEmpId(String value)
    {
        if (value != null)
            value = value.trim();
        setAttributeInternal(EMPID, value);
    }

    /**
     * Gets the attribute value for EMP_NM using the alias name EmpNm.
     * @return the EMP_NM
     */
    public String getEmpNm()
    {
        if (getAttributeInternal(EMPNM) != null)
            return ((String) getAttributeInternal(EMPNM)).trim();
        else
            return ((String) getAttributeInternal(EMPNM));
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NM using the alias name EmpNm.
     * @param value value to set the EMP_NM
     */
    public void setEmpNm(String value)
    {
        if (value != null)
            value = value.trim();
        setAttributeInternal(EMPNM, value);
    }

    /**
     * Gets the attribute value for EMP_NM_1 using the alias name EmpNm1.
     * @return the EMP_NM_1
     */
    public String getEmpNm1()
    {
        return (String) getAttributeInternal(EMPNM1);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NM_1 using the alias name EmpNm1.
     * @param value value to set the EMP_NM_1
     */
    public void setEmpNm1(String value)
    {
        setAttributeInternal(EMPNM1, value);
    }

    /**
     * Gets the attribute value for EMP_NM_2 using the alias name EmpNm2.
     * @return the EMP_NM_2
     */
    public String getEmpNm2()
    {
        return (String) getAttributeInternal(EMPNM2);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NM_2 using the alias name EmpNm2.
     * @param value value to set the EMP_NM_2
     */
    public void setEmpNm2(String value)
    {
        setAttributeInternal(EMPNM2, value);
    }

    /**
     * Gets the attribute value for EMP_NM_3 using the alias name EmpNm3.
     * @return the EMP_NM_3
     */
    public String getEmpNm3()
    {
        return (String) getAttributeInternal(EMPNM3);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NM_3 using the alias name EmpNm3.
     * @param value value to set the EMP_NM_3
     */
    public void setEmpNm3(String value)
    {
        setAttributeInternal(EMPNM3, value);
    }

    /**
     * Gets the attribute value for EMP_NM_4 using the alias name EmpNm4.
     * @return the EMP_NM_4
     */
    public String getEmpNm4()
    {
        return (String) getAttributeInternal(EMPNM4);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NM_4 using the alias name EmpNm4.
     * @param value value to set the EMP_NM_4
     */
    public void setEmpNm4(String value)
    {
        setAttributeInternal(EMPNM4, value);
    }

    /**
     * Gets the attribute value for EMP_CARD_NO using the alias name EmpCardNo.
     * @return the EMP_CARD_NO
     */
    public String getEmpCardNo()
    {
        return (String) getAttributeInternal(EMPCARDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_CARD_NO using the alias name EmpCardNo.
     * @param value value to set the EMP_CARD_NO
     */
    public void setEmpCardNo(String value)
    {
        setAttributeInternal(EMPCARDNO, value);
    }

    /**
     * Gets the attribute value for EMP_DOB using the alias name EmpDob.
     * @return the EMP_DOB
     */
    public Timestamp getEmpDob()
    {
        return (Timestamp) getAttributeInternal(EMPDOB);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_DOB using the alias name EmpDob.
     * @param value value to set the EMP_DOB
     */
    public void setEmpDob(Timestamp value)
    {
        setAttributeInternal(EMPDOB, value);
    }

    /**
     * Gets the attribute value for EMP_DOJ using the alias name EmpDoj.
     * @return the EMP_DOJ
     */
    public Timestamp getEmpDoj()
    {
        return (Timestamp) getAttributeInternal(EMPDOJ);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_DOJ using the alias name EmpDoj.
     * @param value value to set the EMP_DOJ
     */
    public void setEmpDoj(Timestamp value)
    {
        setAttributeInternal(EMPDOJ, value);
    }

    /**
     * Gets the attribute value for EMP_DEPT_ID using the alias name EmpDeptId.
     * @return the EMP_DEPT_ID
     */
    public String getEmpDeptId()
    {
        return (String) getAttributeInternal(EMPDEPTID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_DEPT_ID using the alias name EmpDeptId.
     * @param value value to set the EMP_DEPT_ID
     */
    public void setEmpDeptId(String value)
    {
        setAttributeInternal(EMPDEPTID, value);
    }

    /**
     * Gets the attribute value for EMP_DESG_ID using the alias name EmpDesgId.
     * @return the EMP_DESG_ID
     */
    public String getEmpDesgId()
    {
        return (String) getAttributeInternal(EMPDESGID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_DESG_ID using the alias name EmpDesgId.
     * @param value value to set the EMP_DESG_ID
     */
    public void setEmpDesgId(String value)
    {
        setAttributeInternal(EMPDESGID, value);
    }

    /**
     * Gets the attribute value for EMP_LOC_ID using the alias name EmpLocId.
     * @return the EMP_LOC_ID
     */
    public String getEmpLocId()
    {
        return (String) getAttributeInternal(EMPLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_LOC_ID using the alias name EmpLocId.
     * @param value value to set the EMP_LOC_ID
     */
    public void setEmpLocId(String value)
    {
        setAttributeInternal(EMPLOCID, value);
    }

    /**
     * Gets the attribute value for EMP_GRP_ID using the alias name EmpGrpId.
     * @return the EMP_GRP_ID
     */
    public String getEmpGrpId()
    {
        return (String) getAttributeInternal(EMPGRPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_GRP_ID using the alias name EmpGrpId.
     * @param value value to set the EMP_GRP_ID
     */
    public void setEmpGrpId(String value)
    {
        setAttributeInternal(EMPGRPID, value);
    }

    /**
     * Gets the attribute value for WRK_STAT using the alias name WrkStat.
     * @return the WRK_STAT
     */
    public Integer getWrkStat()
    {
        return (Integer) getAttributeInternal(WRKSTAT);
    }

    /**
     * Sets <code>value</code> as attribute value for WRK_STAT using the alias name WrkStat.
     * @param value value to set the WRK_STAT
     */
    public void setWrkStat(Integer value)
    {
        setAttributeInternal(WRKSTAT, value);
    }

    /**
     * Gets the attribute value for WRK_STAT_DT using the alias name WrkStatDt.
     * @return the WRK_STAT_DT
     */
    public Timestamp getWrkStatDt()
    {
        return (Timestamp) getAttributeInternal(WRKSTATDT);
    }

    /**
     * Sets <code>value</code> as attribute value for WRK_STAT_DT using the alias name WrkStatDt.
     * @param value value to set the WRK_STAT_DT
     */
    public void setWrkStatDt(Timestamp value)
    {
        setAttributeInternal(WRKSTATDT, value);
    }

    /**
     * Gets the attribute value for EMP_GEN using the alias name EmpGen.
     * @return the EMP_GEN
     */
    public String getEmpGen()
    {
        return (String) getAttributeInternal(EMPGEN);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_GEN using the alias name EmpGen.
     * @param value value to set the EMP_GEN
     */
    public void setEmpGen(String value)
    {
        setAttributeInternal(EMPGEN, value);
    }

    /**
     * Gets the attribute value for EMP_DED_CH using the alias name EmpDedCh.
     * @return the EMP_DED_CH
     */
    public String getEmpDedCh()
    {
        return (String) getAttributeInternal(EMPDEDCH);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_DED_CH using the alias name EmpDedCh.
     * @param value value to set the EMP_DED_CH
     */
    public void setEmpDedCh(String value)
    {
        setAttributeInternal(EMPDEDCH, value);
    }

    /**
     * Gets the attribute value for EMP_PERM_ADD using the alias name EmpPermAdd.
     * @return the EMP_PERM_ADD
     */
    public String getEmpPermAdd()
    {
        if (getAttributeInternal(EMPPERMADD) != null)
            return ((String) getAttributeInternal(EMPPERMADD)).trim();
        else
            return (String) getAttributeInternal(EMPPERMADD);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_PERM_ADD using the alias name EmpPermAdd.
     * @param value value to set the EMP_PERM_ADD
     */
    public void setEmpPermAdd(String value)
    {
        if (value != null)
            value = value.trim();
        setAttributeInternal(EMPPERMADD, value);
    }

    /**
     * Gets the attribute value for EMP_CURR_ADD using the alias name EmpCurrAdd.
     * @return the EMP_CURR_ADD
     */
    public String getEmpCurrAdd()
    {
        if (getAttributeInternal(EMPCURRADD) != null)
            return ((String) getAttributeInternal(EMPCURRADD)).trim();
        else
            return (String) getAttributeInternal(EMPCURRADD);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_CURR_ADD using the alias name EmpCurrAdd.
     * @param value value to set the EMP_CURR_ADD
     */
    public void setEmpCurrAdd(String value)
    {
        if (value != null)
            value = value.trim();
        setAttributeInternal(EMPCURRADD, value);
    }

    /**
     * Gets the attribute value for EMP_EMAIL using the alias name EmpEmail.
     * @return the EMP_EMAIL
     */
    public String getEmpEmail()
    {
        return (String) getAttributeInternal(EMPEMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_EMAIL using the alias name EmpEmail.
     * @param value value to set the EMP_EMAIL
     */
    public void setEmpEmail(String value)
    {
        setAttributeInternal(EMPEMAIL, value);
    }

    /**
     * Gets the attribute value for EMP_PHONE1 using the alias name EmpPhone1.
     * @return the EMP_PHONE1
     */
    public String getEmpPhone1()
    {
        return (String) getAttributeInternal(EMPPHONE1);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_PHONE1 using the alias name EmpPhone1.
     * @param value value to set the EMP_PHONE1
     */
    public void setEmpPhone1(String value)
    {
        setAttributeInternal(EMPPHONE1, value);
    }

    /**
     * Gets the attribute value for EMP_PHONE2 using the alias name EmpPhone2.
     * @return the EMP_PHONE2
     */
    public String getEmpPhone2()
    {
        return (String) getAttributeInternal(EMPPHONE2);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_PHONE2 using the alias name EmpPhone2.
     * @param value value to set the EMP_PHONE2
     */
    public void setEmpPhone2(String value)
    {
        setAttributeInternal(EMPPHONE2, value);
    }

    /**
     * Gets the attribute value for EMP_PAY_MODE using the alias name EmpPayMode.
     * @return the EMP_PAY_MODE
     */
    public Integer getEmpPayMode()
    {
        return (Integer) getAttributeInternal(EMPPAYMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_PAY_MODE using the alias name EmpPayMode.
     * @param value value to set the EMP_PAY_MODE
     */
    public void setEmpPayMode(Integer value)
    {
        setAttributeInternal(EMPPAYMODE, value);
    }

    /**
     * Gets the attribute value for EMP_BNK_ID using the alias name EmpBnkId.
     * @return the EMP_BNK_ID
     */
    public Integer getEmpBnkId()
    {
        return (Integer) getAttributeInternal(EMPBNKID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_BNK_ID using the alias name EmpBnkId.
     * @param value value to set the EMP_BNK_ID
     */
    public void setEmpBnkId(Integer value)
    {
        setAttributeInternal(EMPBNKID, value);
    }

    /**
     * Gets the attribute value for BNK_BRNCH_ID using the alias name BnkBrnchId.
     * @return the BNK_BRNCH_ID
     */
    public Integer getBnkBrnchId()
    {
        return (Integer) getAttributeInternal(BNKBRNCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for BNK_BRNCH_ID using the alias name BnkBrnchId.
     * @param value value to set the BNK_BRNCH_ID
     */
    public void setBnkBrnchId(Integer value)
    {
        setAttributeInternal(BNKBRNCHID, value);
    }

    /**
     * Gets the attribute value for ACC_NO using the alias name AccNo.
     * @return the ACC_NO
     */
    public String getAccNo()
    {
        if (getAttributeInternal(ACCNO) != null)
            return ((String) getAttributeInternal(ACCNO)).trim();
        else
            return (String) getAttributeInternal(ACCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_NO using the alias name AccNo.
     * @param value value to set the ACC_NO
     */
    public void setAccNo(String value)
    {
        if (value != null)
            value = value.trim();
        setAttributeInternal(ACCNO, value);
    }

    /**
     * Gets the attribute value for ACC_TYPE using the alias name AccType.
     * @return the ACC_TYPE
     */
    public String getAccType()
    {
        return (String) getAttributeInternal(ACCTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACC_TYPE using the alias name AccType.
     * @param value value to set the ACC_TYPE
     */
    public void setAccType(String value)
    {
        setAttributeInternal(ACCTYPE, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @return the USR_ID_CREATE
     */
    public Integer getUsrIdCreate()
    {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @param value value to set the USR_ID_CREATE
     */
    public void setUsrIdCreate(Integer value)
    {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @return the USR_ID_CREATE_DT
     */
    public Timestamp getUsrIdCreateDt()
    {
        return (Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @param value value to set the USR_ID_CREATE_DT
     */
    public void setUsrIdCreateDt(Timestamp value)
    {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @return the USR_ID_MOD
     */
    public Integer getUsrIdMod()
    {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @param value value to set the USR_ID_MOD
     */
    public void setUsrIdMod(Integer value)
    {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @return the USR_ID_MOD_DT
     */
    public Timestamp getUsrIdModDt()
    {
        return (Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @param value value to set the USR_ID_MOD_DT
     */
    public void setUsrIdModDt(Timestamp value)
    {
        setAttributeInternal(USRIDMODDT, value);
    }

    /**
     * Gets the attribute value for ACTV_FLG using the alias name ActvFlg.
     * @return the ACTV_FLG
     */
    public String getActvFlg()
    {
        return (String) getAttributeInternal(ACTVFLG);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTV_FLG using the alias name ActvFlg.
     * @param value value to set the ACTV_FLG
     */
    public void setActvFlg(String value)
    {
        setAttributeInternal(ACTVFLG, value);
    }

    /**
     * Gets the attribute value for IFSC_CODE using the alias name IfscCode.
     * @return the IFSC_CODE
     */
    public String getIfscCode()
    {
        return (String) getAttributeInternal(IFSCCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for IFSC_CODE using the alias name IfscCode.
     * @param value value to set the IFSC_CODE
     */
    public void setIfscCode(String value)
    {
        setAttributeInternal(IFSCCODE, value);
    }

    /**
     * Gets the attribute value for SWIFT_CODE using the alias name SwiftCode.
     * @return the SWIFT_CODE
     */
    public String getSwiftCode()
    {
        return (String) getAttributeInternal(SWIFTCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SWIFT_CODE using the alias name SwiftCode.
     * @param value value to set the SWIFT_CODE
     */
    public void setSwiftCode(String value)
    {
        setAttributeInternal(SWIFTCODE, value);
    }

    /**
     * Gets the attribute value for EMP_PAN_NO using the alias name EmpPanNo.
     * @return the EMP_PAN_NO
     */
    public String getEmpPanNo()
    {
        return (String) getAttributeInternal(EMPPANNO);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_PAN_NO using the alias name EmpPanNo.
     * @param value value to set the EMP_PAN_NO
     */
    public void setEmpPanNo(String value)
    {
        setAttributeInternal(EMPPANNO, value);
    }

    /**
     * Gets the attribute value for EMP_EO_NM using the alias name EmpEoNm.
     * @return the EMP_EO_NM
     */
    public String getEmpEoNm()
    {
        return (String) getAttributeInternal(EMPEONM);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_EO_NM using the alias name EmpEoNm.
     * @param value value to set the EMP_EO_NM
     */
    public void setEmpEoNm(String value)
    {
        setAttributeInternal(EMPEONM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransGrpDesc.
     * @return the TransGrpDesc
     */
    public String getTransGrpDesc()
    {
        if (getAttributeInternal(TRANSGRPDESC) != null)
            return (String) getAttributeInternal(TRANSGRPDESC);
        else
        {
            HcmEmpPrfAMImpl am = (HcmEmpPrfAMImpl) this.getApplicationModule();
            am.getLovGrp().setNamedWhereClauseParam("cldIdBindVar", this.getCldId());
            am.getLovGrp().setNamedWhereClauseParam("slocIdBindVar", this.getSlocId());
            am.getLovGrp().setNamedWhereClauseParam("hoOrgIdBindVar", this.getHoOrgId());
            am.getLovGrp().setNamedWhereClauseParam("orgIdBindVar", this.getOrgId());
            am.getLovGrp().executeQuery();
            Row[] r = am.getLovGrp().getFilteredRows("GrpId", this.getEmpGrpId());
            if (r.length > 0)
                return (String) r[0].getAttribute("ParamDesc");

            else
                return (String) getAttributeInternal(TRANSGRPDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransGrpDesc.
     * @param value value to set the  TransGrpDesc
     */
    public void setTransGrpDesc(String value)
    {
        setAttributeInternal(TRANSGRPDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBnkNm.
     * @return the TransBnkNm
     */
    public String getTransBnkNm()
    {
        if (getAttributeInternal(TRANSBNKNM) != null)
            return (String) getAttributeInternal(TRANSBNKNM);
        else
        {
            HcmEmpPrfAMImpl am = (HcmEmpPrfAMImpl) this.getApplicationModule();
            am.getLovBankId().setNamedWhereClauseParam("cldIdBindVar", this.getCldId());
            am.getLovBankId().setNamedWhereClauseParam("slocIdBindVar", this.getSlocId());
            am.getLovBankId().setNamedWhereClauseParam("hoOrgIdBindVar", this.getHoOrgId());
            am.getLovBankId().executeQuery();
            Row[] r = am.getLovBankId().getFilteredRows("EoId", this.getEmpBnkId());
            if (r.length > 0)
                return (String) r[0].getAttribute("EoNm");
            else
                return (String) getAttributeInternal(TRANSBNKNM);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBnkNm.
     * @param value value to set the  TransBnkNm
     */
    public void setTransBnkNm(String value)
    {
        setAttributeInternal(TRANSBNKNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransBnkBrnchNm.
     * @return the TransBnkBrnchNm
     */
    public String getTransBnkBrnchNm()
    {
        if (getAttributeInternal(TRANSBNKBRNCHNM) != null)
            return (String) getAttributeInternal(TRANSBNKBRNCHNM);
        else
        {
            HcmEmpPrfAMImpl am = (HcmEmpPrfAMImpl) this.getApplicationModule();
            am.getLovBnkBrnchId().setNamedWhereClauseParam("cldIdBindVar", this.getCldId());
            am.getLovBnkBrnchId().setNamedWhereClauseParam("slocIdBindVar", this.getSlocId());
            am.getLovBnkBrnchId().setNamedWhereClauseParam("hoOrgIdBindVar", this.getHoOrgId());
            am.getLovBnkBrnchId().setNamedWhereClauseParam("mstIdBindVar", this.getEmpBnkId());
            am.getLovBnkBrnchId().executeQuery();
            Row[] r = am.getLovBnkBrnchId().getFilteredRows("EoId", this.getBnkBrnchId());
            if (r.length > 0)
                return (String) r[0].getAttribute("EoNm");
            else
                return (String) getAttributeInternal(TRANSBNKBRNCHNM);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransBnkBrnchNm.
     * @param value value to set the  TransBnkBrnchNm
     */
    public void setTransBnkBrnchNm(String value)
    {
        setAttributeInternal(TRANSBNKBRNCHNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransStrtDtShiftDisp.
     * @return the TransStrtDtShiftDisp
     */
    public Timestamp getTransStrtDtShiftDisp()
    {
        return (Timestamp) getAttributeInternal(TRANSSTRTDTSHIFTDISP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransStrtDtShiftDisp.
     * @param value value to set the  TransStrtDtShiftDisp
     */
    public void setTransStrtDtShiftDisp(Timestamp value)
    {
        setAttributeInternal(TRANSSTRTDTSHIFTDISP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransEndDtShiftDisp.
     * @return the TransEndDtShiftDisp
     */
    public Timestamp getTransEndDtShiftDisp()
    {
        return (Timestamp) getAttributeInternal(TRANSENDDTSHIFTDISP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransEndDtShiftDisp.
     * @param value value to set the  TransEndDtShiftDisp
     */
    public void setTransEndDtShiftDisp(Timestamp value)
    {
        setAttributeInternal(TRANSENDDTSHIFTDISP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransStrtDtTimeCal.
     * @return the TransStrtDtTimeCal
     */
    public Timestamp getTransStrtDtTimeCal()
    {
        Date currDt = new Date(System.currentTimeMillis());
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currDt);
        int year = calendar.get(Calendar.YEAR);
        int month = calendar.get(Calendar.MONTH);
        GregorianCalendar gc = new GregorianCalendar(year, month, 1);
        java.util.Date monthStartDate = new java.util.Date(gc.getTime().getTime());
        if (monthStartDate != null)
            return new Timestamp(monthStartDate);
        else
            return (Timestamp) getAttributeInternal(TRANSSTRTDTTIMECAL);
    }

    /**
     * Gets the attribute value for the calculated attribute TransEndDtTimeCal.
     * @return the TransEndDtTimeCal
     */
    public Timestamp getTransEndDtTimeCal()
    {
        Date currDt = new Date(System.currentTimeMillis());
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(currDt);
        int year = calendar.get(Calendar.YEAR); //(int) ((currDt.getTime()) / (1000 * 60 * 60 * 24 * 365));
        int month = calendar.get(Calendar.MONTH);
        GregorianCalendar gc = new GregorianCalendar(year, month, 1);
        java.util.Date monthStartDate = new java.util.Date(gc.getTime().getTime());
        calendar.setTime(monthStartDate);
        calendar.add(calendar.MONTH, 1);
        calendar.add(calendar.DAY_OF_MONTH, -1);
        Date monthEndDate = (calendar.getTime());
        if (monthEndDate != null)
            return new Timestamp(monthEndDate);
        else
            return (Timestamp) getAttributeInternal(TRANSENDDTTIMECAL);
    }

    /**
     * Gets the attribute value for the calculated attribute TransMode.
     * @return the TransMode
     */
    public String getTransMode()
    {
        if (resolvEl("#{pageFlowScope.MODE_OFF_DTL}") != null)
            return (String) resolvEl("#{pageFlowScope.MODE_OFF_DTL}");
        else
            return "V";
        // return (String) getAttributeInternal(TRANSMODE);
    }


    public String resolvEl(String data)
    {
        FacesContext fc = FacesContext.getCurrentInstance();
        Application app = fc.getApplication();
        ExpressionFactory elFactory = app.getExpressionFactory();
        ELContext elContext = fc.getELContext();
        ValueExpression valueExp = elFactory.createValueExpression(elContext, data, Object.class);
        String msg = null;
        if (valueExp.getValue(elContext) != null)
            msg = valueExp.getValue(elContext).toString();
        return msg;
    }


    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransMode.
     * @param value value to set the  TransMode
     */
    public void setTransMode(String value)
    {
        setAttributeInternal(TRANSMODE, value);
    }

    /**
     * Gets the attribute value for EMP_GUARD_NM using the alias name EmpGuardNm.
     * @return the EMP_GUARD_NM
     */
    public String getEmpGuardNm()
    {
        if (getAttributeInternal(EMPGUARDNM) != null)
            return ((String) getAttributeInternal(EMPGUARDNM)).trim();
        else
            return ((String) getAttributeInternal(EMPGUARDNM));
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_GUARD_NM using the alias name EmpGuardNm.
     * @param value value to set the EMP_GUARD_NM
     */
    public void setEmpGuardNm(String value)
    {
        if (value != null)
            value = value.trim();
        setAttributeInternal(EMPGUARDNM, value);
    }

    /**
     * Gets the attribute value for EMP_REL using the alias name EmpRel.
     * @return the EMP_REL
     */
    public String getEmpRel()
    {
        return (String) getAttributeInternal(EMPREL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_REL using the alias name EmpRel.
     * @param value value to set the EMP_REL
     */
    public void setEmpRel(String value)
    {
        setAttributeInternal(EMPREL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransIsEmpEditable.
     * @return the TransIsEmpEditable
     */
    public String getTransIsEmpEditable()
    {
        Integer wrkStat = getWrkStat();
        if (wrkStat != null)
        {
            if (!wrkStat.equals(31))
                return "Y";
            else
            {
                return "N";
            }
        }
        return (String) getAttributeInternal(TRANSISEMPEDITABLE);
    }

    /**
     * Gets the attribute value for REQ_AREA_FLG using the alias name ReqAreaFlg.
     * @return the REQ_AREA_FLG
     */
    public String getReqAreaFlg()
    {
        return (String) getAttributeInternal(REQAREAFLG);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_AREA_FLG using the alias name ReqAreaFlg.
     * @param value value to set the REQ_AREA_FLG
     */
    public void setReqAreaFlg(String value)
    {
        setAttributeInternal(REQAREAFLG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransIsRqmtButtonAvl.
     * @return the TransIsRqmtButtonAvl
     */
    public String getTransIsRqmtButtonAvl()
    {
        String flag = getReqAreaFlg();
        System.out.println("Flag value " + flag);
        if (flag != null)
        {
            if (flag.equals("Y"))
            {
                return "N";
            }
            if (flag.equals("N"))
            {
                return "Y";
            }
        }
        else
        {
            return "Y";
        }

        return (String) getAttributeInternal(TRANSISRQMTBUTTONAVL);
    }

    /**
     * Gets the attribute value for SPON_NM using the alias name SponNm.
     * @return the SPON_NM
     */
    public String getSponNm()
    {
        return (String) getAttributeInternal(SPONNM);
    }

    /**
     * Sets <code>value</code> as attribute value for SPON_NM using the alias name SponNm.
     * @param value value to set the SPON_NM
     */
    public void setSponNm(String value)
    {
        setAttributeInternal(SPONNM, value);
    }

    /**
     * Gets the attribute value for EMP_MRTL_STAT using the alias name EmpMrtlStat.
     * @return the EMP_MRTL_STAT
     */
    public Integer getEmpMrtlStat()
    {
        return (Integer) getAttributeInternal(EMPMRTLSTAT);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_MRTL_STAT using the alias name EmpMrtlStat.
     * @param value value to set the EMP_MRTL_STAT
     */
    public void setEmpMrtlStat(Integer value)
    {
        setAttributeInternal(EMPMRTLSTAT, value);
    }

    /**
     * Gets the attribute value for EMP_NATION using the alias name EmpNation.
     * @return the EMP_NATION
     */
    public Integer getEmpNation()
    {
        return (Integer) getAttributeInternal(EMPNATION);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NATION using the alias name EmpNation.
     * @param value value to set the EMP_NATION
     */
    public void setEmpNation(Integer value)
    {
        setAttributeInternal(EMPNATION, value);
    }

    /**
     * Gets the attribute value for MGR_CODE using the alias name MgrCode.
     * @return the MGR_CODE
     */
    public Integer getMgrCode()
    {
        return (Integer) getAttributeInternal(MGRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for MGR_CODE using the alias name MgrCode.
     * @param value value to set the MGR_CODE
     */
    public void setMgrCode(Integer value)
    {
        setAttributeInternal(MGRCODE, value);
    }

    /**
     * Gets the attribute value for MGR_DOC_ID using the alias name MgrDocId.
     * @return the MGR_DOC_ID
     */
    public String getMgrDocId()
    {
        return (String) getAttributeInternal(MGRDOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for MGR_DOC_ID using the alias name MgrDocId.
     * @param value value to set the MGR_DOC_ID
     */
    public void setMgrDocId(String value)
    {
        setAttributeInternal(MGRDOCID, value);
    }

    /**
     * Gets the attribute value for USR_ID using the alias name UsrId.
     * @return the USR_ID
     */
    public Integer getUsrId()
    {
        return (Integer) getAttributeInternal(USRID);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID using the alias name UsrId.
     * @param value value to set the USR_ID
     */
    public void setUsrId(Integer value)
    {
        setAttributeInternal(USRID, value);
    }

    /**
     * Gets the attribute value for EMP_RET_DT using the alias name EmpRetDt.
     * @return the EMP_RET_DT
     */
    public Timestamp getEmpRetDt()
    {
        return (Timestamp) getAttributeInternal(EMPRETDT);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_RET_DT using the alias name EmpRetDt.
     * @param value value to set the EMP_RET_DT
     */
    public void setEmpRetDt(Timestamp value)
    {
        setAttributeInternal(EMPRETDT, value);
    }

    /**
     * Gets the attribute value for EMP_CONF_DT using the alias name EmpConfDt.
     * @return the EMP_CONF_DT
     */
    public Timestamp getEmpConfDt()
    {
        return (Timestamp) getAttributeInternal(EMPCONFDT);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_CONF_DT using the alias name EmpConfDt.
     * @param value value to set the EMP_CONF_DT
     */
    public void setEmpConfDt(Timestamp value)
    {
        setAttributeInternal(EMPCONFDT, value);
    }

    /**
     * Gets the attribute value for BNK_CODE using the alias name BnkCode.
     * @return the BNK_CODE
     */
    public String getBnkCode()
    {
        return (String) getAttributeInternal(BNKCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for BNK_CODE using the alias name BnkCode.
     * @param value value to set the BNK_CODE
     */
    public void setBnkCode(String value)
    {
        setAttributeInternal(BNKCODE, value);
    }

    /**
     * Gets the attribute value for EMP_WRK_HOURS using the alias name EmpWrkHours.
     * @return the EMP_WRK_HOURS
     */
    public oracle.jbo.domain.Number getEmpWrkHours()
    {

        if (getEmpGrpId() != null && getAttributeInternal(EMPWRKHOURS) == null)
        {
            HcmEmpPrfAMImpl am = (HcmEmpPrfAMImpl) this.getApplicationModule();
            am.getLovGrp().setNamedWhereClauseParam("cldIdBindVar", this.getCldId());
            am.getLovGrp().setNamedWhereClauseParam("slocIdBindVar", this.getSlocId());
            am.getLovGrp().setNamedWhereClauseParam("hoOrgIdBindVar", this.getHoOrgId());
            am.getLovGrp().setNamedWhereClauseParam("orgIdBindVar", this.getOrgId());
            am.getLovGrp().executeQuery();
            Row[] r = am.getLovGrp().getFilteredRows("GrpId", this.getEmpGrpId());
            if (r.length > 0)
            {
                if (r[0].getAttribute("GrpHrsWgesChk") != null)
                {
                    if (r[0].getAttribute("GrpHrsWgesChk").equals("Y") && r[0].getAttribute("GrpHrs") != null)
                    {
                        setEmpWrkHours((Number) r[0].getAttribute("GrpHrs"));
                        return (Number) r[0].getAttribute("GrpHrs");
                    }
                }
                return (oracle.jbo.domain.Number) getAttributeInternal(EMPWRKHOURS);
            }
            return (oracle.jbo.domain.Number) getAttributeInternal(EMPWRKHOURS);
        }
        return (oracle.jbo.domain.Number) getAttributeInternal(EMPWRKHOURS);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_WRK_HOURS using the alias name EmpWrkHours.
     * @param value value to set the EMP_WRK_HOURS
     */
    public void setEmpWrkHours(oracle.jbo.domain.Number value)
    {
        setAttributeInternal(EMPWRKHOURS, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TransGrpWagesChk.
     * @return the TransGrpWagesChk
     */
    public String getTransGrpWagesChk()
    {
        if (getEmpGrpId() != null)
        {
            HcmEmpPrfAMImpl am = (HcmEmpPrfAMImpl) this.getApplicationModule();
            am.getLovGrp().setNamedWhereClauseParam("cldIdBindVar", this.getCldId());
            am.getLovGrp().setNamedWhereClauseParam("slocIdBindVar", this.getSlocId());
            am.getLovGrp().setNamedWhereClauseParam("hoOrgIdBindVar", this.getHoOrgId());
            am.getLovGrp().setNamedWhereClauseParam("orgIdBindVar", this.getOrgId());
            am.getLovGrp().executeQuery();
            Row[] r = am.getLovGrp().getFilteredRows("GrpId", this.getEmpGrpId());
            if (r.length > 0)
            {
                if (r[0].getAttribute("GrpHrsWgesChk") != null)
                {

                    return r[0].getAttribute("GrpHrsWgesChk").toString();
                }
                else
                {
                    return "N";
                }
            }
        }
        return (String) getAttributeInternal(TRANSGRPWAGESCHK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransGrpWagesChk.
     * @param value value to set the  TransGrpWagesChk
     */
    public void setTransGrpWagesChk(String value)
    {
        setAttributeInternal(TRANSGRPWAGESCHK, value);
    }

    /**
     * Gets the attribute value for EMP_BLD_GRP using the alias name EmpBldGrp.
     * @return the EMP_BLD_GRP
     */
    public String getEmpBldGrp()
    {
        return (String) getAttributeInternal(EMPBLDGRP);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_BLD_GRP using the alias name EmpBldGrp.
     * @param value value to set the EMP_BLD_GRP
     */
    public void setEmpBldGrp(String value)
    {
        setAttributeInternal(EMPBLDGRP, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TransCntryId.
     * @return the TransCntryId
     */
    public Integer getTransCntryId()
    {
        HcmEmpPrfAMImpl am = (HcmEmpPrfAMImpl) this.getApplicationModule();
        am.getOrgCntryVO1().setNamedWhereClauseParam("cldIdBindVar", getCldId());
        am.getOrgCntryVO1().setNamedWhereClauseParam("hoOrgIdBindVar", getHoOrgId());
        am.getOrgCntryVO1().setNamedWhereClauseParam("orgIdBindVar", getOrgId());
        am.getOrgCntryVO1().executeQuery();
        Row r[] = am.getOrgCntryVO1().getFilteredRows("OrgId", getOrgId());
        if (r.length > 0)
        {
            System.out.println("country id in getter--->" + r[0].getAttribute("OrgCountryId"));
            return (Integer) r[0].getAttribute("OrgCountryId");
        }
        return (Integer) getAttributeInternal(TRANSCNTRYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransCntryId.
     * @param value value to set the  TransCntryId
     */
    public void setTransCntryId(Integer value)
    {
        setAttributeInternal(TRANSCNTRYID, value);
    }

    /**
     * Gets the attribute value for EMP_NOTICE using the alias name EmpNotice.
     * @return the EMP_NOTICE
     */
    public Integer getEmpNotice()
    {
        return (Integer) getAttributeInternal(EMPNOTICE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NOTICE using the alias name EmpNotice.
     * @param value value to set the EMP_NOTICE
     */
    public void setEmpNotice(Integer value)
    {
        setAttributeInternal(EMPNOTICE, value);
    }

    /**
     * Gets the attribute value for EMP_DOL using the alias name EmpDol.
     * @return the EMP_DOL
     */
    public Timestamp getEmpDol()
    {
        return (Timestamp) getAttributeInternal(EMPDOL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_DOL using the alias name EmpDol.
     * @param value value to set the EMP_DOL
     */
    public void setEmpDol(Timestamp value)
    {
        setAttributeInternal(EMPDOL, value);
    }

    /**
     * Gets the attribute value for GRD_ID using the alias name GrdId.
     * @return the GRD_ID
     */
    public String getGrdId()
    {
        return (String) getAttributeInternal(GRDID);
    }

    /**
     * Sets <code>value</code> as attribute value for GRD_ID using the alias name GrdId.
     * @param value value to set the GRD_ID
     */
    public void setGrdId(String value)
    {
        setAttributeInternal(GRDID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute transGradSalChck.
     * @return the transGradSalChck
     */
    public String gettransGradSalChck()
    {
        String gradChk = getIsLinkAvlbl("GradeSalPay");
        return gradChk;
        //return (String) getAttributeInternal(TRANSGRADSALCHCK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute transGradSalChck.
     * @param value value to set the  transGradSalChck
     */
    public void settransGradSalChck(String value)
    {
        setAttributeInternal(TRANSGRADSALCHCK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute transReffraanceEmpChk.
     * @return the transReffraanceEmpChk
     */
    public String gettransReffraanceEmpChk()
    {
        String empRefChhk = getIsLinkAvlbl("EmployeReffChk");
        return empRefChhk;
        //return (String) getAttributeInternal(TRANSREFFRAANCEEMPCHK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute transReffraanceEmpChk.
     * @param value value to set the  transReffraanceEmpChk
     */
    public void settransReffraanceEmpChk(String value)
    {
        setAttributeInternal(TRANSREFFRAANCEEMPCHK, value);
    }

    /**
     * Gets the attribute value for EMP_REF_DOC_ID using the alias name EmpRefDocId.
     * @return the EMP_REF_DOC_ID
     */
    public String getEmpRefDocId()
    {
        return (String) getAttributeInternal(EMPREFDOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_REF_DOC_ID using the alias name EmpRefDocId.
     * @param value value to set the EMP_REF_DOC_ID
     */
    public void setEmpRefDocId(String value)
    {
        setAttributeInternal(EMPREFDOCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute transEmpRefNm.
     * @return the transEmpRefNm
     */
    public String gettransEmpRefNm()
    {
        if (this.getEmpRefDocId() != null)
        {
            HcmEmpPrfAMImpl am = (HcmEmpPrfAMImpl) this.getApplicationModule();
            am.getLovEmpNmForReffrance1().setNamedWhereClauseParam("cldIdBind", this.getCldId());
            am.getLovEmpNmForReffrance1().setNamedWhereClauseParam("slocIdBind", this.getSlocId());
            am.getLovEmpNmForReffrance1().setNamedWhereClauseParam("hoOrgIdBind", this.getHoOrgId());
            am.getLovEmpNmForReffrance1().setNamedWhereClauseParam("orgIdBind", this.getOrgId());
            am.getLovEmpNmForReffrance1().executeQuery();
            Row[] r = am.getLovEmpNmForReffrance1().getFilteredRows("DocId", this.getEmpRefDocId());
            if (r.length > 0)
            {
                return (String) r[0].getAttribute("EmpNm");
            }

        }

        return (String) getAttributeInternal(TRANSEMPREFNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute transEmpRefNm.
     * @param value value to set the  transEmpRefNm
     */
    public void settransEmpRefNm(String value)
    {
        setAttributeInternal(TRANSEMPREFNM, value);
    }

    /**
     * Gets the attribute value for EMP_TYPE using the alias name EmpType.
     * @return the EMP_TYPE
     */
    public Integer getEmpType()
    {
        return (Integer) getAttributeInternal(EMPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_TYPE using the alias name EmpType.
     * @param value value to set the EMP_TYPE
     */
    public void setEmpType(Integer value)
    {
        setAttributeInternal(EMPTYPE, value);
    }

    /**
     * Gets the attribute value for EMP_PROBATION using the alias name EmpProbation.
     * @return the EMP_PROBATION
     */
    public Integer getEmpProbation()
    {
        return (Integer) getAttributeInternal(EMPPROBATION);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_PROBATION using the alias name EmpProbation.
     * @param value value to set the EMP_PROBATION
     */
    public void setEmpProbation(Integer value)
    {
        setAttributeInternal(EMPPROBATION, value);
    }

    /**
     * Gets the attribute value for EMP_CURR_PIN using the alias name EmpCurrPin.
     * @return the EMP_CURR_PIN
     */
    public Integer getEmpCurrPin() {
        return (Integer) getAttributeInternal(EMPCURRPIN);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_CURR_PIN using the alias name EmpCurrPin.
     * @param value value to set the EMP_CURR_PIN
     */
    public void setEmpCurrPin(Integer value) {
        setAttributeInternal(EMPCURRPIN, value);
    }

    /**
     * Gets the attribute value for EMP_PERM_PIN using the alias name EmpPermPin.
     * @return the EMP_PERM_PIN
     */
    public Integer getEmpPermPin() {
        return (Integer) getAttributeInternal(EMPPERMPIN);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_PERM_PIN using the alias name EmpPermPin.
     * @param value value to set the EMP_PERM_PIN
     */
    public void setEmpPermPin(Integer value) {
        setAttributeInternal(EMPPERMPIN, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpImg.
     */
    public RowIterator getHcmEmpImg()
    {
        return (RowIterator) getAttributeInternal(HCMEMPIMG);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpSal.
     */
    public RowIterator getHcmEmpSal()
    {
        return (RowIterator) getAttributeInternal(HCMEMPSAL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpLeave.
     */
    public RowIterator getHcmEmpLeave()
    {
        return (RowIterator) getAttributeInternal(HCMEMPLEAVE);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpCalOff.
     */
    public RowIterator getHcmEmpCalOff()
    {
        return (RowIterator) getAttributeInternal(HCMEMPCALOFF);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpShift.
     */
    public RowIterator getHcmEmpShift()
    {
        return (RowIterator) getAttributeInternal(HCMEMPSHIFT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EmployeeDeduction.
     */
    public RowIterator getEmployeeDeduction()
    {
        return (RowIterator) getAttributeInternal(EMPLOYEEDEDUCTION);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpShiftTmp.
     */
    public RowIterator getHcmEmpShiftTmp()
    {
        return (RowIterator) getAttributeInternal(HCMEMPSHIFTTMP);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpSkil.
     */
    public RowIterator getHcmEmpSkil()
    {
        return (RowIterator) getAttributeInternal(HCMEMPSKIL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RqmtArea.
     */
    public RowIterator getRqmtArea()
    {
        return (RowIterator) getAttributeInternal(RQMTAREA);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link OrgHcmEmpOthDtl.
     */
    public RowIterator getOrgHcmEmpOthDtl()
    {
        return (RowIterator) getAttributeInternal(ORGHCMEMPOTHDTL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpDocAttch.
     */
    public RowIterator getHcmEmpDocAttch()
    {
        return (RowIterator) getAttributeInternal(HCMEMPDOCATTCH);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpDpndDtl.
     */
    public RowIterator getHcmEmpDpndDtl()
    {
        return (RowIterator) getAttributeInternal(HCMEMPDPNDDTL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpMdclDtl.
     */
    public RowIterator getHcmEmpMdclDtl()
    {
        return (RowIterator) getAttributeInternal(HCMEMPMDCLDTL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpExpVo.
     */
    public RowIterator getHcmEmpExpVo()
    {
        return (RowIterator) getAttributeInternal(HCMEMPEXPVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpLang.
     */
    public RowIterator getHcmEmpLang()
    {
        return (RowIterator) getAttributeInternal(HCMEMPLANG);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link HcmEmpQuali.
     */
    public RowIterator getHcmEmpQuali()
    {
        return (RowIterator) getAttributeInternal(HCMEMPQUALI);
    }


    /**
     * Gets the view accessor <code>RowSet</code> LovDesgIdVO.
     */
    public RowSet getLovDesgIdVO()
    {
        return (RowSet) getAttributeInternal(LOVDESGIDVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovDeptIdVO.
     */
    public RowSet getLovDeptIdVO()
    {
        System.out.println("mode in rowimpl=" + getTransMode());
        RowSet rs = (RowSet) getAttributeInternal(LOVDEPTIDVO);
        rs.setNamedWhereClauseParam("cldIdBindVar", getCldId());
        rs.setNamedWhereClauseParam("hoOrgIdBindVar", getHoOrgId());
        rs.setNamedWhereClauseParam("orgIdBindVar", getOrgId());
        rs.setNamedWhereClauseParam("slocIdBindVar", getSlocId());
        if (getTransMode() != null && getTransMode().equals("A"))
            rs.setNamedWhereClauseParam("actvBind", "Y");
        else
            rs.setNamedWhereClauseParam("actvBind", null);
        rs.executeQuery();
        return rs;

        // return (RowSet) getAttributeInternal(LOVDEPTIDVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovGrpVO.
     */
    public RowSet getLovGrpVO()
    {
        System.out.println("mode in rowimpl=" + getTransMode());

        RowSet rs = (RowSet) getAttributeInternal(LOVGRPVO);
        rs.setNamedWhereClauseParam("cldIdBindVar", getCldId());
        rs.setNamedWhereClauseParam("hoOrgIdBindVar", getHoOrgId());
        rs.setNamedWhereClauseParam("orgIdBindVar", getOrgId());
        rs.setNamedWhereClauseParam("slocIdBindVar", getSlocId());
        if (getTransMode() != null && getTransMode().equals("A"))
            rs.setNamedWhereClauseParam("actvBindVar", "Y");
        else
            rs.setNamedWhereClauseParam("actvBindVar", null);
        rs.executeQuery();
        return rs;

        //  return (RowSet) getAttributeInternal(LOVGRPVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovGenderVO.
     */
    public RowSet getLovGenderVO()
    {
        return (RowSet) getAttributeInternal(LOVGENDERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovLocationVO.
     */
    public RowSet getLovLocationVO()
    {
        System.out.println("mode in rowimpl=" + getTransMode());

        RowSet rs = (RowSet) getAttributeInternal(LOVLOCATIONVO);
        rs.setNamedWhereClauseParam("cldIdBindVar", getCldId());
        rs.setNamedWhereClauseParam("hoOrgIdBindVar", getHoOrgId());
        rs.setNamedWhereClauseParam("orgIdBindVar", getOrgId());
        rs.setNamedWhereClauseParam("slocIdBindVar", getSlocId());
        if (getTransMode() != null && getTransMode().equals("A"))
            rs.setNamedWhereClauseParam("actvBind", "Y");
        else
            rs.setNamedWhereClauseParam("actvBind", null);
        rs.executeQuery();
        return rs;
        // return (RowSet) getAttributeInternal(LOVLOCATIONVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovAccTypeVO.
     */
    public RowSet getLovAccTypeVO()
    {

        return (RowSet) getAttributeInternal(LOVACCTYPEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovPayModeVO.
     */
    public RowSet getLovPayModeVO()
    {
        return (RowSet) getAttributeInternal(LOVPAYMODEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovBankIdVO.
     */
    public RowSet getLovBankIdVO()
    {
        return (RowSet) getAttributeInternal(LOVBANKIDVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovBnkBrnchIdVO.
     */
    public RowSet getLovBnkBrnchIdVO()
    {
        return (RowSet) getAttributeInternal(LOVBNKBRNCHIDVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovEmpStat.
     */
    public RowSet getLovEmpStat()
    {
        return (RowSet) getAttributeInternal(LOVEMPSTAT);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovMaritalStatusVO1.
     */
    public RowSet getLovMaritalStatusVO1()
    {
        return (RowSet) getAttributeInternal(LOVMARITALSTATUSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovNationalityVO1.
     */
    public RowSet getLovNationalityVO1()
    {
        return (RowSet) getAttributeInternal(LOVNATIONALITYVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovUsrIdVO1.
     */
    public RowSet getLovUsrIdVO1()
    {
        return (RowSet) getAttributeInternal(LOVUSRIDVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovManagerVO1.
     */
    public RowSet getLovManagerVO1()
    {
        return (RowSet) getAttributeInternal(LOVMANAGERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovGrdNmVO1.
     */
    public RowSet getLovGrdNmVO1()
    {
        return (RowSet) getAttributeInternal(LOVGRDNMVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovEmpNmForReffranceVO1.
     */
    public RowSet getLovEmpNmForReffranceVO1()
    {
        return (RowSet) getAttributeInternal(LOVEMPNMFORREFFRANCEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovEmpTypeO1.
     */
    public RowSet getLovEmpTypeO1()
    {
        return (RowSet) getAttributeInternal(LOVEMPTYPEO1);
    }

    public String getIsLinkAvlbl(String type)
    {
        String result = "";
        HcmEmpPrfAMImpl am = (HcmEmpPrfAMImpl) this.getApplicationModule();
        String cldId = EbizParams.GLBL_APP_CLD_ID();
        Integer slocId = EbizParams.GLBL_APP_SERV_LOC();
        String orgId = EbizParams.GLBL_APP_USR_ORG();
        ViewObjectImpl vo = am.getOrgHcmPrf();
        RowQualifier rqhcmprf = new RowQualifier(vo);
        rqhcmprf.setWhereClause("CldId='" + cldId + "' and SlocId=" + slocId + " and OrgId='" + orgId + "' ");
        Row[] rw = vo.getFilteredRows(rqhcmprf);
        if (rw != null && rw.length > 0)
        {
            for (Row r : rw)
            {
                if (type.equals("GradeSalPay"))
                {
                    result = (String) r.getAttribute("GradePayChk");
                }
                if (type.equals("EmployeReffChk"))
                {
                    result = (String) r.getAttribute("EmpRefChk");
                }


            }
        }
        return result;
    }
}

