package mnfWorkStationApp.model.entities;


import adf.utils.ebiz.EbizParams;

import org.apache.myfaces.trinidad.context.RequestContext;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;

import java.sql.Types;

import java.util.Iterator;

import javax.el.ELContext;
import javax.el.ExpressionFactory;
import javax.el.ValueExpression;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;

import mnfWorkStationApp.model.services.MNFWorkStationAppAMImpl;

import java.lang.String;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowInconsistentException;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.Entity;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;

import oracle.jdbc.OracleTypes;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 21 15:34:01 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnfWsEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CldId,
        SlocId,
        HoOrgId,
        WsId,
        WsDesc,
        WsType,
        WsBasis,
        WsLegCd,
        WcId,
        WsCapType,
        CapUom,
        MaxCap,
        AvgCap,
        CapHours,
        WsLineNo,
        WsLineType,
        WsPoDt,
        WsPutDt,
        WsWarrantyExpDt,
        WsMntType,
        WsEffPer,
        WsDefFlg,
        WsSuppId,
        WsSuppAdds,
        WsPurAmt,
        WsActv,
        WsInactvReason,
        WsInactvDate,
        WsRmrk,
        UsrIdCreate,
        UsrIdCreateDt,
        UsrIdMod,
        UsrIdModDt,
        WsInvNo,
        RefWsId,
        WsModelNo,
        WsSrNo,
        WsInvDt,
        MnfWsAttch,
        MnfWsCap,
        MnfWsParam,
        MnfWsRes,
        MnfWsShift,
        MnfWsOrg,
        MnfWsAMC;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int SLOCID = AttributesEnum.SlocId.index();
    public static final int HOORGID = AttributesEnum.HoOrgId.index();
    public static final int WSID = AttributesEnum.WsId.index();
    public static final int WSDESC = AttributesEnum.WsDesc.index();
    public static final int WSTYPE = AttributesEnum.WsType.index();
    public static final int WSBASIS = AttributesEnum.WsBasis.index();
    public static final int WSLEGCD = AttributesEnum.WsLegCd.index();
    public static final int WCID = AttributesEnum.WcId.index();
    public static final int WSCAPTYPE = AttributesEnum.WsCapType.index();
    public static final int CAPUOM = AttributesEnum.CapUom.index();
    public static final int MAXCAP = AttributesEnum.MaxCap.index();
    public static final int AVGCAP = AttributesEnum.AvgCap.index();
    public static final int CAPHOURS = AttributesEnum.CapHours.index();
    public static final int WSLINENO = AttributesEnum.WsLineNo.index();
    public static final int WSLINETYPE = AttributesEnum.WsLineType.index();
    public static final int WSPODT = AttributesEnum.WsPoDt.index();
    public static final int WSPUTDT = AttributesEnum.WsPutDt.index();
    public static final int WSWARRANTYEXPDT = AttributesEnum.WsWarrantyExpDt.index();
    public static final int WSMNTTYPE = AttributesEnum.WsMntType.index();
    public static final int WSEFFPER = AttributesEnum.WsEffPer.index();
    public static final int WSDEFFLG = AttributesEnum.WsDefFlg.index();
    public static final int WSSUPPID = AttributesEnum.WsSuppId.index();
    public static final int WSSUPPADDS = AttributesEnum.WsSuppAdds.index();
    public static final int WSPURAMT = AttributesEnum.WsPurAmt.index();
    public static final int WSACTV = AttributesEnum.WsActv.index();
    public static final int WSINACTVREASON = AttributesEnum.WsInactvReason.index();
    public static final int WSINACTVDATE = AttributesEnum.WsInactvDate.index();
    public static final int WSRMRK = AttributesEnum.WsRmrk.index();
    public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
    public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
    public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
    public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
    public static final int WSINVNO = AttributesEnum.WsInvNo.index();
    public static final int REFWSID = AttributesEnum.RefWsId.index();
    public static final int WSMODELNO = AttributesEnum.WsModelNo.index();
    public static final int WSSRNO = AttributesEnum.WsSrNo.index();
    public static final int WSINVDT = AttributesEnum.WsInvDt.index();
    public static final int MNFWSATTCH = AttributesEnum.MnfWsAttch.index();
    public static final int MNFWSCAP = AttributesEnum.MnfWsCap.index();
    public static final int MNFWSPARAM = AttributesEnum.MnfWsParam.index();
    public static final int MNFWSRES = AttributesEnum.MnfWsRes.index();
    public static final int MNFWSSHIFT = AttributesEnum.MnfWsShift.index();
    public static final int MNFWSORG = AttributesEnum.MnfWsOrg.index();
    public static final int MNFWSAMC = AttributesEnum.MnfWsAMC.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnfWsEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("mnfWorkStationApp.model.entities.MnfWsEO");
    }


    /**
     * Gets the attribute value for CldId, using the alias name CldId.
     * @return the value of CldId
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CldId.
     * @param value value to set the CldId
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for SlocId, using the alias name SlocId.
     * @return the value of SlocId
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SlocId.
     * @param value value to set the SlocId
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for HoOrgId, using the alias name HoOrgId.
     * @return the value of HoOrgId
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HoOrgId.
     * @param value value to set the HoOrgId
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for WsId, using the alias name WsId.
     * @return the value of WsId
     */
    public String getWsId() {
        return (String) getAttributeInternal(WSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsId.
     * @param value value to set the WsId
     */
    public void setWsId(String value) {
        setAttributeInternal(WSID, value);
    }

    /**
     * Gets the attribute value for WsDesc, using the alias name WsDesc.
     * @return the value of WsDesc
     */
    public String getWsDesc() {
        return (String) getAttributeInternal(WSDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsDesc.
     * @param value value to set the WsDesc
     */
    public void setWsDesc(String value) {
        setAttributeInternal(WSDESC, value);
    }

    /**
     * Gets the attribute value for WsType, using the alias name WsType.
     * @return the value of WsType
     */
    public Integer getWsType() {
        return (Integer) getAttributeInternal(WSTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsType.
     * @param value value to set the WsType
     */
    public void setWsType(Integer value) {
        setAttributeInternal(WSTYPE, value);
    }

    /**
     * Gets the attribute value for WsBasis, using the alias name WsBasis.
     * @return the value of WsBasis
     */
    public Integer getWsBasis() {
        return (Integer) getAttributeInternal(WSBASIS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsBasis.
     * @param value value to set the WsBasis
     */
    public void setWsBasis(Integer value) {
        setAttributeInternal(WSBASIS, value);
    }

    /**
     * Gets the attribute value for WsLegCd, using the alias name WsLegCd.
     * @return the value of WsLegCd
     */
    public String getWsLegCd() {
        return (String) getAttributeInternal(WSLEGCD);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsLegCd.
     * @param value value to set the WsLegCd
     */
    public void setWsLegCd(String value) {
        setAttributeInternal(WSLEGCD, value);
    }


    /**
     * Gets the attribute value for WcId, using the alias name WcId.
     * @return the value of WcId
     */
    public String getWcId() {
        return (String) getAttributeInternal(WCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WcId.
     * @param value value to set the WcId
     */
    public void setWcId(String value) {
        setAttributeInternal(WCID, value);
    }

    /**
     * Gets the attribute value for WsCapType, using the alias name WsCapType.
     * @return the value of WsCapType
     */
    public Integer getWsCapType() {
        return (Integer) getAttributeInternal(WSCAPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsCapType.
     * @param value value to set the WsCapType
     */
    public void setWsCapType(Integer value) {
        setAttributeInternal(WSCAPTYPE, value);
    }

    /**
     * Gets the attribute value for CapUom, using the alias name CapUom.
     * @return the value of CapUom
     */
    public String getCapUom() {
        return (String) getAttributeInternal(CAPUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for CapUom.
     * @param value value to set the CapUom
     */
    public void setCapUom(String value) {
        setAttributeInternal(CAPUOM, value);
    }

    /**
     * Gets the attribute value for MaxCap, using the alias name MaxCap.
     * @return the value of MaxCap
     */
    public Number getMaxCap() {
        return (Number) getAttributeInternal(MAXCAP);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxCap.
     * @param value value to set the MaxCap
     */
    public void setMaxCap(Number value) {
        setAttributeInternal(MAXCAP, value);
    }

    /**
     * Gets the attribute value for AvgCap, using the alias name AvgCap.
     * @return the value of AvgCap
     */
    public Number getAvgCap() {
        return (Number) getAttributeInternal(AVGCAP);
    }

    /**
     * Sets <code>value</code> as the attribute value for AvgCap.
     * @param value value to set the AvgCap
     */
    public void setAvgCap(Number value) {
        setAttributeInternal(AVGCAP, value);
    }

    /**
     * Gets the attribute value for CapHours, using the alias name CapHours.
     * @return the value of CapHours
     */
    public Integer getCapHours() {
        return (Integer) getAttributeInternal(CAPHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CapHours.
     * @param value value to set the CapHours
     */
    public void setCapHours(Integer value) {
        setAttributeInternal(CAPHOURS, value);
    }

    /**
     * Gets the attribute value for WsLineNo, using the alias name WsLineNo.
     * @return the value of WsLineNo
     */
    public String getWsLineNo() {
        return (String) getAttributeInternal(WSLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsLineNo.
     * @param value value to set the WsLineNo
     */
    public void setWsLineNo(String value) {
        setAttributeInternal(WSLINENO, value);
    }

    /**
     * Gets the attribute value for WsLineType, using the alias name WsLineType.
     * @return the value of WsLineType
     */
    public Integer getWsLineType() {
        return (Integer) getAttributeInternal(WSLINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsLineType.
     * @param value value to set the WsLineType
     */
    public void setWsLineType(Integer value) {
        setAttributeInternal(WSLINETYPE, value);
    }

    /**
     * Gets the attribute value for WsPoDt, using the alias name WsPoDt.
     * @return the value of WsPoDt
     */
    public Timestamp getWsPoDt() {
        return (Timestamp) getAttributeInternal(WSPODT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsPoDt.
     * @param value value to set the WsPoDt
     */
    public void setWsPoDt(Timestamp value) {
        setAttributeInternal(WSPODT, value);
    }

    /**
     * Gets the attribute value for WsPutDt, using the alias name WsPutDt.
     * @return the value of WsPutDt
     */
    public Timestamp getWsPutDt() {
        return (Timestamp) getAttributeInternal(WSPUTDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsPutDt.
     * @param value value to set the WsPutDt
     */
    public void setWsPutDt(Timestamp value) {
        setAttributeInternal(WSPUTDT, value);
    }

    /**
     * Gets the attribute value for WsWarrantyExpDt, using the alias name WsWarrantyExpDt.
     * @return the value of WsWarrantyExpDt
     */
    public Timestamp getWsWarrantyExpDt() {
        return (Timestamp) getAttributeInternal(WSWARRANTYEXPDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsWarrantyExpDt.
     * @param value value to set the WsWarrantyExpDt
     */
    public void setWsWarrantyExpDt(Timestamp value) {
        setAttributeInternal(WSWARRANTYEXPDT, value);
    }

    /**
     * Gets the attribute value for WsMntType, using the alias name WsMntType.
     * @return the value of WsMntType
     */
    public Integer getWsMntType() {
        return (Integer) getAttributeInternal(WSMNTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsMntType.
     * @param value value to set the WsMntType
     */
    public void setWsMntType(Integer value) {
        setAttributeInternal(WSMNTTYPE, value);
    }

    /**
     * Gets the attribute value for WsEffPer, using the alias name WsEffPer.
     * @return the value of WsEffPer
     */
    public Number getWsEffPer() {
        return (Number) getAttributeInternal(WSEFFPER);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsEffPer.
     * @param value value to set the WsEffPer
     */
    public void setWsEffPer(Number value) {
        setAttributeInternal(WSEFFPER, value);
    }


    /**
     * Gets the attribute value for WsDefFlg, using the alias name WsDefFlg.
     * @return the value of WsDefFlg
     */
    public String getWsDefFlg() {
        return (String) getAttributeInternal(WSDEFFLG);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsDefFlg.
     * @param value value to set the WsDefFlg
     */
    public void setWsDefFlg(String value) {
        setAttributeInternal(WSDEFFLG, value);
    }

    /**
     * Gets the attribute value for WsSuppId, using the alias name WsSuppId.
     * @return the value of WsSuppId
     */
    public Integer getWsSuppId() {
        return (Integer) getAttributeInternal(WSSUPPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsSuppId.
     * @param value value to set the WsSuppId
     */
    public void setWsSuppId(Integer value) {
        setAttributeInternal(WSSUPPID, value);
    }

    /**
     * Gets the attribute value for WsSuppAdds, using the alias name WsSuppAdds.
     * @return the value of WsSuppAdds
     */
    public String getWsSuppAdds() {
        return (String) getAttributeInternal(WSSUPPADDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsSuppAdds.
     * @param value value to set the WsSuppAdds
     */
    public void setWsSuppAdds(String value) {
        setAttributeInternal(WSSUPPADDS, value);
    }

    /**
     * Gets the attribute value for WsPurAmt, using the alias name WsPurAmt.
     * @return the value of WsPurAmt
     */
    public Number getWsPurAmt() {
        return (Number) getAttributeInternal(WSPURAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsPurAmt.
     * @param value value to set the WsPurAmt
     */
    public void setWsPurAmt(Number value) {
        setAttributeInternal(WSPURAMT, value);
    }

    /**
     * Gets the attribute value for WsActv, using the alias name WsActv.
     * @return the value of WsActv
     */
    public String getWsActv() {
        return (String) getAttributeInternal(WSACTV);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsActv.
     * @param value value to set the WsActv
     */
    public void setWsActv(String value) {
        setAttributeInternal(WSACTV, value);
    }

    /**
     * Gets the attribute value for WsInactvReason, using the alias name WsInactvReason.
     * @return the value of WsInactvReason
     */
    public String getWsInactvReason() {
        return (String) getAttributeInternal(WSINACTVREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsInactvReason.
     * @param value value to set the WsInactvReason
     */
    public void setWsInactvReason(String value) {
        setAttributeInternal(WSINACTVREASON, value);
    }

    /**
     * Gets the attribute value for WsInactvDate, using the alias name WsInactvDate.
     * @return the value of WsInactvDate
     */
    public Timestamp getWsInactvDate() {
        return (Timestamp) getAttributeInternal(WSINACTVDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsInactvDate.
     * @param value value to set the WsInactvDate
     */
    public void setWsInactvDate(Timestamp value) {
        setAttributeInternal(WSINACTVDATE, value);
    }

    /**
     * Gets the attribute value for WsRmrk, using the alias name WsRmrk.
     * @return the value of WsRmrk
     */
    public String getWsRmrk() {
        return (String) getAttributeInternal(WSRMRK);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsRmrk.
     * @param value value to set the WsRmrk
     */
    public void setWsRmrk(String value) {
        setAttributeInternal(WSRMRK, value);
    }

    /**
     * Gets the attribute value for UsrIdCreate, using the alias name UsrIdCreate.
     * @return the value of UsrIdCreate
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdCreate.
     * @param value value to set the UsrIdCreate
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for UsrIdCreateDt, using the alias name UsrIdCreateDt.
     * @return the value of UsrIdCreateDt
     */
    public Timestamp getUsrIdCreateDt() {
        return (Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdCreateDt.
     * @param value value to set the UsrIdCreateDt
     */
    public void setUsrIdCreateDt(Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for UsrIdMod, using the alias name UsrIdMod.
     * @return the value of UsrIdMod
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdMod.
     * @param value value to set the UsrIdMod
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for UsrIdModDt, using the alias name UsrIdModDt.
     * @return the value of UsrIdModDt
     */
    public Timestamp getUsrIdModDt() {
        return (Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsrIdModDt.
     * @param value value to set the UsrIdModDt
     */
    public void setUsrIdModDt(Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }

    /**
     * Gets the attribute value for WsInvNo, using the alias name WsInvNo.
     * @return the value of WsInvNo
     */
    public String getWsInvNo() {
        return (String) getAttributeInternal(WSINVNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsInvNo.
     * @param value value to set the WsInvNo
     */
    public void setWsInvNo(String value) {
        setAttributeInternal(WSINVNO, value);
    }

    /**
     * Gets the attribute value for RefWsId, using the alias name RefWsId.
     * @return the value of RefWsId
     */
    public String getRefWsId() {
        return (String) getAttributeInternal(REFWSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefWsId.
     * @param value value to set the RefWsId
     */
    public void setRefWsId(String value) {
        setAttributeInternal(REFWSID, value);
    }

    /**
     * Gets the attribute value for WsModelNo, using the alias name WsModelNo.
     * @return the value of WsModelNo
     */
    public String getWsModelNo() {
        return (String) getAttributeInternal(WSMODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsModelNo.
     * @param value value to set the WsModelNo
     */
    public void setWsModelNo(String value) {
        setAttributeInternal(WSMODELNO, value);
    }

    /**
     * Gets the attribute value for WsSrNo, using the alias name WsSrNo.
     * @return the value of WsSrNo
     */
    public String getWsSrNo() {
        return (String) getAttributeInternal(WSSRNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsSrNo.
     * @param value value to set the WsSrNo
     */
    public void setWsSrNo(String value) {
        setAttributeInternal(WSSRNO, value);
    }

    /**
     * Gets the attribute value for WsInvDt, using the alias name WsInvDt.
     * @return the value of WsInvDt
     */
    public Timestamp getWsInvDt() {
        return (Timestamp) getAttributeInternal(WSINVDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WsInvDt.
     * @param value value to set the WsInvDt
     */
    public void setWsInvDt(Timestamp value) {
        setAttributeInternal(WSINVDT, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnfWsAttch() {
        return (RowIterator) getAttributeInternal(MNFWSATTCH);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnfWsCap() {
        return (RowIterator) getAttributeInternal(MNFWSCAP);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnfWsParam() {
        return (RowIterator) getAttributeInternal(MNFWSPARAM);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnfWsRes() {
        return (RowIterator) getAttributeInternal(MNFWSRES);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnfWsShift() {
        return (RowIterator) getAttributeInternal(MNFWSSHIFT);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnfWsOrg() {
        return (RowIterator) getAttributeInternal(MNFWSORG);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnfWsAMC() {
        return (RowIterator) getAttributeInternal(MNFWSAMC);
    }


    /**
     * @param cldId key constituent
     * @param slocId key constituent
     * @param hoOrgId key constituent
     * @param wsId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String cldId, Integer slocId, String hoOrgId, String wsId) {
        return new Key(new Object[] { cldId, slocId, hoOrgId, wsId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        //setAttributeInternal(USRIDCREATE, Integer.parseInt(resolvEl("#{pageFlowScope.GLBL_APP_USR}").toString()));
        if(EbizParams.GLBL_APP_USR() != null)
                {
                    setUsrIdCreate(EbizParams.GLBL_APP_USR());
                }
        setUsrIdCreateDt(new oracle.jbo.domain.Timestamp(new java.util.Date()));
        setWsDefFlg("N");

        if (getWSNoFunc() != null)
            setWsId(getWSNoFunc());

        // #{pageFlowScope.ATTACH_MANPOWER}
        Map pageFlowScope = ADFContext.getCurrent().getPageFlowScope();
        pageFlowScope.put("ATTACH_MANPOWER", chkOrgPrf());

        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */

    public void lock() {
       /* try {
            /*    super.lock();
        } catch (RowInconsistentException e) {
            refresh(REFRESH_WITH_DB_ONLY_IF_UNCHANGED | REFRESH_CONTAINEES);
            super.lock();
        } */
    }


    /**Method to resolve page flow scope parameter.*/

    public Object resolvEl_(String data) {
        FacesContext fc = FacesContext.getCurrentInstance();
        Application app = fc.getApplication();
        ExpressionFactory elFactory = app.getExpressionFactory();
        ELContext elContext = fc.getELContext();
        ValueExpression valueExp = elFactory.createValueExpression(elContext, data, Object.class);
        Object Message = valueExp.getValue(elContext).toString();
        return Message;
    }


    /**----------------------------------------------------------------**/

    /**Method to resolve page flow scope parameter.*/
    public Object resolvEl(String data) {
        ADFContext adfCtx = ADFContext.getCurrent();
        ELContext elContext = adfCtx.getELContext();
        ValueExpression valueExp = adfCtx.getExpressionFactory().createValueExpression(elContext, data, Object.class);
        Object Message = valueExp.getValue(elContext);
        return Message;
    }

    /**----------------------------------------------------------------**/

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        if (operation == DML_UPDATE) {
            //setAttributeInternal(USRIDMOD, Integer.parseInt(resolvEl("#{pageFlowScope.GLBL_APP_USR}").toString()));
            if(EbizParams.GLBL_APP_USR() != null)
                    {
                        setUsrIdMod(EbizParams.GLBL_APP_USR());
                    }
            setUsrIdModDt(new oracle.jbo.domain.Timestamp(System.currentTimeMillis()));
        }
        super.doDML(operation, e);

    }


    /********************    STORED Function    *************************************/

    protected Object callStoredFunction(int sqlReturnType, String stmt, Object[] bindVars) {
        CallableStatement st = null;
        try {
            st = this.getDBTransaction().createCallableStatement("begin ? := " + stmt + ";end;", 0);
            st.registerOutParameter(1, sqlReturnType);
            if (bindVars != null) {
                for (int z = 0; z < bindVars.length; z++) {
                    st.setObject(z + 2, bindVars[z]);
                    // System.out.println(bindVars[z] + "zzzzzzzzzzzzzzzzzzzzz");
                }
            }
            st.executeUpdate();
            // System.out.println("aaaaaaaaaaaaaaaaaaa");
            return st.getObject(1);
        } catch (SQLException e) {
            e.printStackTrace();
            throw new JboException(e);
        } finally {
            if (st != null) {
                try {
                    st.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    /** ---------- To create WorkStation Id -------------**/

    public String getWSNoFunc() {

        String workStationId = null;
        try {
            workStationId = this.callStoredFunction(Types.VARCHAR, "MNF.FN_MNF_GET_PRF_ID(?,?,?,?,?,?,?,?)", new Object[] {
                                                    this.getSlocId(), this.getCldId(), this.getHoOrgId(),
                                                    this.getHoOrgId(), 25505, null, "MNF$WS", 0
            }).toString();


        } catch (Exception e) {
            e.printStackTrace();
            // System.out.println("ERROR IN CALLING FUNCTION :" + e.getMessage());
        }
        // System.out.println("===========" + workStationId);

        return workStationId;

    }
    /***---------------------------------------------------------**/

    /**
     *
     * Function to attach man power at workstation or not
     *
     * **/
    public String chkOrgPrf() {

        String dummy = null;
        try {

            dummy = callStoredFunction(Types.VARCHAR, "fn_mnf_chk_org_prf(?,?,?,?)", new Object[] {
                                       this.getCldId(), this.getSlocId(), this.getHoOrgId(), "ATTACH_MANPWR_WS"
            }).toString();
        } catch (Exception ex) {
            throw new JboException(ex);
        }
        // System.out.println("Value of Dummy is : " + dummy);
        return dummy;

    }

}

