package mmsoctktakeapp.model.entity;

import java.math.BigDecimal;

import javax.el.ELContext;
import javax.el.ExpressionFactory;
import javax.el.ValueExpression;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;

import mmsoctktakeapp.model.services.MMStkTakeAMImpl;

import mmsoctktakeapp.model.view.ItemTransVOImpl;
import mmsoctktakeapp.model.view.MmStkTakeItmVOImpl;
import mmsoctktakeapp.model.view.MmStkTakeVOImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 07 18:08:48 IST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MmStkTakeLotEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CldId {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getCldId();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setCldId((String) value);
            }
        }
        ,
        SlocId {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getSlocId();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setSlocId((Integer) value);
            }
        }
        ,
        OrgId {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setOrgId((String) value);
            }
        }
        ,
        WhId {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getWhId();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setWhId((String) value);
            }
        }
        ,
        DocId {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getDocId();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setDocId((String) value);
            }
        }
        ,
        LotId {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getLotId();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setLotId((String) value);
            }
        }
        ,
        ItmId {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getItmId();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setItmId((String) value);
            }
        }
        ,
        ItmUom {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getItmUom();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setItmUom((String) value);
            }
        }
        ,
        TotQty {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getTotQty();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setTotQty((BigDecimal) value);
            }
        }
        ,
        PhyQty {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getPhyQty();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setPhyQty((BigDecimal) value);
            }
        }
        ,
        DiffQty {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getDiffQty();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setDiffQty((BigDecimal) value);
            }
        }
        ,
        ScrpQty {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getScrpQty();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setScrpQty((BigDecimal) value);
            }
        }
        ,
        RwkQty {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getRwkQty();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setRwkQty((BigDecimal) value);
            }
        }
        ,
        DiffType {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getDiffType();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setDiffType((String) value);
            }
        }
        ,
        LotRemarks {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getLotRemarks();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setLotRemarks((String) value);
            }
        }
        ,
        MmStkTakeItm {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getMmStkTakeItm();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setMmStkTakeItm((MmStkTakeItmEOImpl) value);
            }
        }
        ,
        MmStkTakeSr {
            public Object get(MmStkTakeLotEOImpl obj) {
                return obj.getMmStkTakeSr();
            }

            public void put(MmStkTakeLotEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MmStkTakeLotEOImpl object);

        public abstract void put(MmStkTakeLotEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int SLOCID = AttributesEnum.SlocId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int WHID = AttributesEnum.WhId.index();
    public static final int DOCID = AttributesEnum.DocId.index();
    public static final int LOTID = AttributesEnum.LotId.index();
    public static final int ITMID = AttributesEnum.ItmId.index();
    public static final int ITMUOM = AttributesEnum.ItmUom.index();
    public static final int TOTQTY = AttributesEnum.TotQty.index();
    public static final int PHYQTY = AttributesEnum.PhyQty.index();
    public static final int DIFFQTY = AttributesEnum.DiffQty.index();
    public static final int SCRPQTY = AttributesEnum.ScrpQty.index();
    public static final int RWKQTY = AttributesEnum.RwkQty.index();
    public static final int DIFFTYPE = AttributesEnum.DiffType.index();
    public static final int LOTREMARKS = AttributesEnum.LotRemarks.index();
    public static final int MMSTKTAKEITM = AttributesEnum.MmStkTakeItm.index();
    public static final int MMSTKTAKESR = AttributesEnum.MmStkTakeSr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MmStkTakeLotEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("mmsoctktakeapp.model.entity.MmStkTakeLotEO");
    }


    /**
     * Gets the attribute value for CldId, using the alias name CldId.
     * @return the value of CldId
     */
    public String getCldId() {
        return (String)getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CldId.
     * @param value value to set the CldId
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for SlocId, using the alias name SlocId.
     * @return the value of SlocId
     */
    public Integer getSlocId() {
        return (Integer)getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SlocId.
     * @param value value to set the SlocId
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the value of OrgId
     */
    public String getOrgId() {
        return (String)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(String value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for WhId, using the alias name WhId.
     * @return the value of WhId
     */
    public String getWhId() {
        return (String)getAttributeInternal(WHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WhId.
     * @param value value to set the WhId
     */
    public void setWhId(String value) {
        setAttributeInternal(WHID, value);
    }

    /**
     * Gets the attribute value for DocId, using the alias name DocId.
     * @return the value of DocId
     */
    public String getDocId() {
        return (String)getAttributeInternal(DOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocId.
     * @param value value to set the DocId
     */
    public void setDocId(String value) {
        setAttributeInternal(DOCID, value);
    }

    /**
     * Gets the attribute value for LotId, using the alias name LotId.
     * @return the value of LotId
     */
    public String getLotId() {
        return (String)getAttributeInternal(LOTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LotId.
     * @param value value to set the LotId
     */
    public void setLotId(String value) {
        setAttributeInternal(LOTID, value);
    }

    /**
     * Gets the attribute value for ItmId, using the alias name ItmId.
     * @return the value of ItmId
     */
    public String getItmId() {
        return (String)getAttributeInternal(ITMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItmId.
     * @param value value to set the ItmId
     */
    public void setItmId(String value) {
        setAttributeInternal(ITMID, value);
    }

    /**
     * Gets the attribute value for ItmUom, using the alias name ItmUom.
     * @return the value of ItmUom
     */
    public String getItmUom() {
        return (String)getAttributeInternal(ITMUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItmUom.
     * @param value value to set the ItmUom
     */
    public void setItmUom(String value) {
        setAttributeInternal(ITMUOM, value);
    }

    /**
     * Gets the attribute value for TotQty, using the alias name TotQty.
     * @return the value of TotQty
     */
    public BigDecimal getTotQty() {
        return (BigDecimal)getAttributeInternal(TOTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotQty.
     * @param value value to set the TotQty
     */
    public void setTotQty(BigDecimal value) {
        setAttributeInternal(TOTQTY, value);
    }

    /**
     * Gets the attribute value for PhyQty, using the alias name PhyQty.
     * @return the value of PhyQty
     */
    public BigDecimal getPhyQty() {
        return (BigDecimal)getAttributeInternal(PHYQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhyQty.
     * @param value value to set the PhyQty
     */
    public void setPhyQty(BigDecimal value) {
        setAttributeInternal(PHYQTY, value);
    }

    /**
     * Gets the attribute value for DiffQty, using the alias name DiffQty.
     * @return the value of DiffQty
     */
    public BigDecimal getDiffQty() {
        return (BigDecimal)getAttributeInternal(DIFFQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiffQty.
     * @param value value to set the DiffQty
     */
    public void setDiffQty(BigDecimal value) {
        setAttributeInternal(DIFFQTY, value);
    }

    /**
     * Gets the attribute value for ScrpQty, using the alias name ScrpQty.
     * @return the value of ScrpQty
     */
    public BigDecimal getScrpQty() {
        return (BigDecimal)getAttributeInternal(SCRPQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScrpQty.
     * @param value value to set the ScrpQty
     */
    public void setScrpQty(BigDecimal value) {
        setAttributeInternal(SCRPQTY, value);
    }

    /**
     * Gets the attribute value for RwkQty, using the alias name RwkQty.
     * @return the value of RwkQty
     */
    public BigDecimal getRwkQty() {
        return (BigDecimal)getAttributeInternal(RWKQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RwkQty.
     * @param value value to set the RwkQty
     */
    public void setRwkQty(BigDecimal value) {
        setAttributeInternal(RWKQTY, value);
    }

    /**
     * Gets the attribute value for DiffType, using the alias name DiffType.
     * @return the value of DiffType
     */
    public String getDiffType() {
        return (String)getAttributeInternal(DIFFTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DiffType.
     * @param value value to set the DiffType
     */
    public void setDiffType(String value) {
        setAttributeInternal(DIFFTYPE, value);
    }

    /**
     * Gets the attribute value for LotRemarks, using the alias name LotRemarks.
     * @return the value of LotRemarks
     */
    public String getLotRemarks() {
        return (String) getAttributeInternal(LOTREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for LotRemarks.
     * @param value value to set the LotRemarks
     */
    public void setLotRemarks(String value) {
        setAttributeInternal(LOTREMARKS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity MmStkTakeItmEOImpl.
     */
    public MmStkTakeItmEOImpl getMmStkTakeItm() {
        return (MmStkTakeItmEOImpl)getAttributeInternal(MMSTKTAKEITM);
    }

    /**
     * Sets <code>value</code> as the associated entity MmStkTakeItmEOImpl.
     */
    public void setMmStkTakeItm(MmStkTakeItmEOImpl value) {
        setAttributeInternal(MMSTKTAKEITM, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMmStkTakeSr() {
        return (RowIterator)getAttributeInternal(MMSTKTAKESR);
    }


    /**
     * @param cldId key constituent
     * @param slocId key constituent
     * @param orgId key constituent
     * @param whId key constituent
     * @param docId key constituent
     * @param lotId key constituent
     * @param itmId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String cldId, Integer slocId, String orgId, String whId, String docId,
                                       String lotId, String itmId) {
        return new Key(new Object[] { cldId, slocId, orgId, whId, docId, lotId, itmId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {   
        setScrpQty(BigDecimal.ZERO);
        setRwkQty(BigDecimal.ZERO);
        super.create(attributeList);
    }
    public Object resolvElDC(String data) {
    FacesContext fc = FacesContext.getCurrentInstance();
    Application app = fc.getApplication();
    ExpressionFactory elFactory = app.getExpressionFactory();
    ELContext elContext = fc.getELContext();
    ValueExpression valueExp =
    elFactory.createValueExpression(elContext, "#{data." + data + ".dataProvider}", Object.class);
    return valueExp.getValue(elContext);
    }
    
    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
