package svcwarrantyprfapp.model.views;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;

import svcwarrantyprfapp.model.entities.AppItmWtyEOImpl;
import svcwarrantyprfapp.model.services.SvcWarrantyPrFAMImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 14 13:47:32 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppItmWtyVORowImpl extends ViewRowImpl {


    public static final int ENTITY_APPITMWTYEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CldId,
        SlocId,
        HoOrgId,
        ItmId,
        WtyId,
        WtyDflt,
        Actv,
        InactvDt,
        InactvResn,
        UsrIdCreate,
        UsrIdCreateDt,
        UsrIdMod,
        UsrIdModDt,
        transappname,
        LovItemNameVO1,
        LovItemNameVO2;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CLDID = AttributesEnum.CldId.index();
    public static final int SLOCID = AttributesEnum.SlocId.index();
    public static final int HOORGID = AttributesEnum.HoOrgId.index();
    public static final int ITMID = AttributesEnum.ItmId.index();
    public static final int WTYID = AttributesEnum.WtyId.index();
    public static final int WTYDFLT = AttributesEnum.WtyDflt.index();
    public static final int ACTV = AttributesEnum.Actv.index();
    public static final int INACTVDT = AttributesEnum.InactvDt.index();
    public static final int INACTVRESN = AttributesEnum.InactvResn.index();
    public static final int USRIDCREATE = AttributesEnum.UsrIdCreate.index();
    public static final int USRIDCREATEDT = AttributesEnum.UsrIdCreateDt.index();
    public static final int USRIDMOD = AttributesEnum.UsrIdMod.index();
    public static final int USRIDMODDT = AttributesEnum.UsrIdModDt.index();
    public static final int TRANSAPPNAME = AttributesEnum.transappname.index();
    public static final int LOVITEMNAMEVO1 = AttributesEnum.LovItemNameVO1.index();
    public static final int LOVITEMNAMEVO2 = AttributesEnum.LovItemNameVO2.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AppItmWtyVORowImpl() {
    }

    /**
     * Gets AppItmWtyEO entity object.
     * @return the AppItmWtyEO
     */
    public AppItmWtyEOImpl getAppItmWtyEO() {
        return (AppItmWtyEOImpl) getEntity(ENTITY_APPITMWTYEO);
    }

    /**
     * Gets the attribute value for CLD_ID using the alias name CldId.
     * @return the CLD_ID
     */
    public String getCldId() {
        return (String) getAttributeInternal(CLDID);
    }

    /**
     * Sets <code>value</code> as attribute value for CLD_ID using the alias name CldId.
     * @param value value to set the CLD_ID
     */
    public void setCldId(String value) {
        setAttributeInternal(CLDID, value);
    }

    /**
     * Gets the attribute value for SLOC_ID using the alias name SlocId.
     * @return the SLOC_ID
     */
    public Integer getSlocId() {
        return (Integer) getAttributeInternal(SLOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for SLOC_ID using the alias name SlocId.
     * @param value value to set the SLOC_ID
     */
    public void setSlocId(Integer value) {
        setAttributeInternal(SLOCID, value);
    }

    /**
     * Gets the attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @return the HO_ORG_ID
     */
    public String getHoOrgId() {
        return (String) getAttributeInternal(HOORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for HO_ORG_ID using the alias name HoOrgId.
     * @param value value to set the HO_ORG_ID
     */
    public void setHoOrgId(String value) {
        setAttributeInternal(HOORGID, value);
    }

    /**
     * Gets the attribute value for ITM_ID using the alias name ItmId.
     * @return the ITM_ID
     */
    public String getItmId() {
        return (String) getAttributeInternal(ITMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITM_ID using the alias name ItmId.
     * @param value value to set the ITM_ID
     */
    public void setItmId(String value) {
        setAttributeInternal(ITMID, value);
    }

    /**
     * Gets the attribute value for WTY_ID using the alias name WtyId.
     * @return the WTY_ID
     */
    public String getWtyId() {
        return (String) getAttributeInternal(WTYID);
    }

    /**
     * Sets <code>value</code> as attribute value for WTY_ID using the alias name WtyId.
     * @param value value to set the WTY_ID
     */
    public void setWtyId(String value) {
        setAttributeInternal(WTYID, value);
    }

    /**
     * Gets the attribute value for WTY_DFLT using the alias name WtyDflt.
     * @return the WTY_DFLT
     */
    public String getWtyDflt() {
        return (String) getAttributeInternal(WTYDFLT);
    }

    /**
     * Sets <code>value</code> as attribute value for WTY_DFLT using the alias name WtyDflt.
     * @param value value to set the WTY_DFLT
     */
    public void setWtyDflt(String value) {
        setAttributeInternal(WTYDFLT, value);
    }

    /**
     * Gets the attribute value for ACTV using the alias name Actv.
     * @return the ACTV
     */
    public String getActv() {
        return (String) getAttributeInternal(ACTV);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTV using the alias name Actv.
     * @param value value to set the ACTV
     */
    public void setActv(String value) {
        setAttributeInternal(ACTV, value);
    }

    /**
     * Gets the attribute value for INACTV_DT using the alias name InactvDt.
     * @return the INACTV_DT
     */
    public Timestamp getInactvDt() {
        return (Timestamp) getAttributeInternal(INACTVDT);
    }

    /**
     * Sets <code>value</code> as attribute value for INACTV_DT using the alias name InactvDt.
     * @param value value to set the INACTV_DT
     */
    public void setInactvDt(Timestamp value) {
        setAttributeInternal(INACTVDT, value);
    }

    /**
     * Gets the attribute value for INACTV_RESN using the alias name InactvResn.
     * @return the INACTV_RESN
     */
    public String getInactvResn() {
        return (String) getAttributeInternal(INACTVRESN);
    }

    /**
     * Sets <code>value</code> as attribute value for INACTV_RESN using the alias name InactvResn.
     * @param value value to set the INACTV_RESN
     */
    public void setInactvResn(String value) {
        setAttributeInternal(INACTVRESN, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @return the USR_ID_CREATE
     */
    public Integer getUsrIdCreate() {
        return (Integer) getAttributeInternal(USRIDCREATE);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE using the alias name UsrIdCreate.
     * @param value value to set the USR_ID_CREATE
     */
    public void setUsrIdCreate(Integer value) {
        setAttributeInternal(USRIDCREATE, value);
    }

    /**
     * Gets the attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @return the USR_ID_CREATE_DT
     */
    public Timestamp getUsrIdCreateDt() {
        return (Timestamp) getAttributeInternal(USRIDCREATEDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_CREATE_DT using the alias name UsrIdCreateDt.
     * @param value value to set the USR_ID_CREATE_DT
     */
    public void setUsrIdCreateDt(Timestamp value) {
        setAttributeInternal(USRIDCREATEDT, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @return the USR_ID_MOD
     */
    public Integer getUsrIdMod() {
        return (Integer) getAttributeInternal(USRIDMOD);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD using the alias name UsrIdMod.
     * @param value value to set the USR_ID_MOD
     */
    public void setUsrIdMod(Integer value) {
        setAttributeInternal(USRIDMOD, value);
    }

    /**
     * Gets the attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @return the USR_ID_MOD_DT
     */
    public Timestamp getUsrIdModDt() {
        return (Timestamp) getAttributeInternal(USRIDMODDT);
    }

    /**
     * Sets <code>value</code> as attribute value for USR_ID_MOD_DT using the alias name UsrIdModDt.
     * @param value value to set the USR_ID_MOD_DT
     */
    public void setUsrIdModDt(Timestamp value) {
        setAttributeInternal(USRIDMODDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute transappname.
     * @return the transappname
     */
    public String gettransappname() {
        
        String orgname="";
        SvcWarrantyPrFAMImpl am=(SvcWarrantyPrFAMImpl)this.getApplicationModule();
        ViewObjectImpl vo=am.getLovItemName1();
        vo.setNamedWhereClauseParam("bindcldid", getCldId());
        vo.setNamedWhereClauseParam("bindhoorgid", getHoOrgId());
        vo.setNamedWhereClauseParam("bindslocid", getSlocId());
        vo.executeQuery();
        Row[] r=vo.getFilteredRows("ItmId",this.getItmId());
        System.out.println("value of r------"+r.length);
        if(r.length>0)
        {
            System.out.println("Item name--"+r[0].getAttribute("ItmDesc"));
          orgname=(String) r[0].getAttribute("ItmDesc");
        }
        System.out.println("orgname+++"+orgname);
        return orgname;
       // return (String) getAttributeInternal(TRANSAPPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute transappname.
     * @param value value to set the  transappname
     */
    public void settransappname(String value) {
        setAttributeInternal(TRANSAPPNAME, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovItemNameVO1.
     */
    public RowSet getLovItemNameVO1() {
        return (RowSet) getAttributeInternal(LOVITEMNAMEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LovItemNameVO2.
     */
    public RowSet getLovItemNameVO2() {
        return (RowSet) getAttributeInternal(LOVITEMNAMEVO2);
    }
}

