package taxtype.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 29 14:54:10 IST 2013
// ---------------------------------------------------------------------
public interface AppTaxTypeVO extends ViewObject {
    void setbindVarValue(Integer SlocId, String OrgId, String CldId);
}
