package subcontractreceiptapp.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 16 19:42:01 IST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LovScoDlvItemVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LovScoDlvItemVOImpl() {
    }

    /**
     * Returns the bind variable value for BindCldId.
     * @return bind variable value for BindCldId
     */
    public String getBindCldId() {
        return (String) getNamedWhereClauseParam("BindCldId");
    }

    /**
     * Sets <code>value</code> for bind variable BindCldId.
     * @param value value to bind as BindCldId
     */
    public void setBindCldId(String value) {
        setNamedWhereClauseParam("BindCldId", value);
    }

    /**
     * Returns the bind variable value for BindSlocId.
     * @return bind variable value for BindSlocId
     */
    public Integer getBindSlocId() {
        return (Integer) getNamedWhereClauseParam("BindSlocId");
    }

    /**
     * Sets <code>value</code> for bind variable BindSlocId.
     * @param value value to bind as BindSlocId
     */
    public void setBindSlocId(Integer value) {
        setNamedWhereClauseParam("BindSlocId", value);
    }

    /**
     * Returns the bind variable value for BindHoOrgId.
     * @return bind variable value for BindHoOrgId
     */
    public String getBindHoOrgId() {
        return (String) getNamedWhereClauseParam("BindHoOrgId");
    }

    /**
     * Sets <code>value</code> for bind variable BindHoOrgId.
     * @param value value to bind as BindHoOrgId
     */
    public void setBindHoOrgId(String value) {
        setNamedWhereClauseParam("BindHoOrgId", value);
    }

    /**
     * Returns the bind variable value for BindOrgId.
     * @return bind variable value for BindOrgId
     */
    public String getBindOrgId() {
        return (String) getNamedWhereClauseParam("BindOrgId");
    }

    /**
     * Sets <code>value</code> for bind variable BindOrgId.
     * @param value value to bind as BindOrgId
     */
    public void setBindOrgId(String value) {
        setNamedWhereClauseParam("BindOrgId", value);
    }

    /**
     * Returns the bind variable value for BindDocId.
     * @return bind variable value for BindDocId
     */
    public String getBindDocId() {
        return (String) getNamedWhereClauseParam("BindDocId");
    }

    /**
     * Sets <code>value</code> for bind variable BindDocId.
     * @param value value to bind as BindDocId
     */
    public void setBindDocId(String value) {
        setNamedWhereClauseParam("BindDocId", value);
    }

    /**
     * Returns the bind variable value for BindDlvNo.
     * @return bind variable value for BindDlvNo
     */
    public Integer getBindDlvNo() {
        return (Integer) getNamedWhereClauseParam("BindDlvNo");
    }

    /**
     * Sets <code>value</code> for bind variable BindDlvNo.
     * @param value value to bind as BindDlvNo
     */
    public void setBindDlvNo(Integer value) {
        setNamedWhereClauseParam("BindDlvNo", value);
    }

    /**
     * Returns the bind variable value for BindType.
     * @return bind variable value for BindType
     */
    public Integer getBindType() {
        return (Integer) getNamedWhereClauseParam("BindType");
    }

    /**
     * Sets <code>value</code> for bind variable BindType.
     * @param value value to bind as BindType
     */
    public void setBindType(Integer value) {
        setNamedWhereClauseParam("BindType", value);
    }

    /**
     * Returns the bind variable value for BindItemId.
     * @return bind variable value for BindItemId
     */
    public String getBindItemId() {
        return (String) getNamedWhereClauseParam("BindItemId");
    }

    /**
     * Sets <code>value</code> for bind variable BindItemId.
     * @param value value to bind as BindItemId
     */
    public void setBindItemId(String value) {
        setNamedWhereClauseParam("BindItemId", value);
    }
}

